### PR TITLE
feat(cli, introspection,migrate,sdk): add npm/yarn/npx in front of suggested commands

### LINKED ISSUE #3210: Suggested CLI commands are missing `npx` prefix when being triggered via `npx prisma` itself
Suggestion from @do4gr 
https://github.com/prisma/migrate/issues/529#issue-664346234

Example CLI output when using npx is suggesting to use command `prisma ...` (missing npx at the beginning)
image

### PR DESCRIPTION
**Pull request by Jolg42**
Closes https://github.com/prisma/prisma/issues/3210

### CODE REVIEW

**Comment by Jolg42** [comment]
I'm checking to do it in NodeEngine too

**Comment by janpio** [comment]
> Not done in JavaScript files like preinstall postinstall (because JS).

What does that mean?

**Comment by Jolg42** [comment]
> > Not done in JavaScript files like preinstall postinstall (because JS).
> 
> What does that mean?

That my script is in TypeScript so I would need to do a variant for JavaScript here.

**Comment by janpio** [comment]
> > > Not done in JavaScript files like preinstall postinstall (because JS).
> > 
> > 
> > What does that mean?
> 
> That my script is in TypeScript so I would need to do a variant for JavaScript here.

Do we output any commands here for users to pick up from it?

**Comment by Jolg42** [comment]
Yes we do so we should find a way to do it there too I guess

**Review by janpio — APPROVED** [review]
Looks good to me 👍 

Let's move the leftover JS problem into a new issue that gets a candidate label for next sprint already.

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/issues/3328

**Pull request merged**
