### PR TITLE
feat(get-platform): add FreeBSD 14 as a new platform

### LINKED ISSUE #22228: Add FreeBSD 14 as a new platform
### Bug description

After upgrade to FreeBSD 14-RELEASE I can build new engines, but client is failing:

`PrismaClientInitializationError: Unknown PRISMA_QUERY_ENGINE_LIBRARY freebsd14`

or

`Error: Unknown binary target freebsd14 in generator client.`

### Expected behavior

Please add "freebsd14" string to those files:

```
packages/fetch-engine/src/download.ts
packages/get-platform/src/getPlatform.ts
packages/get-platform/src/platforms.ts
```

### Prisma information

-

### Environment & setup

- OS: FreeBSD 14-RELEASE
- Database: PostgreSQL
- Node.js version: v18.18.2

### Prisma Version

```
5.5.2
```

### PR DESCRIPTION
**Pull request by tinola**
Closes: https://github.com/prisma/prisma/issues/22228

### CODE REVIEW

**Comment by aqrln** [comment]
Thanks for the PR @tinola, could you please sign the CLA so we can merge it? (see the message above)

Re: https://github.com/prisma/prisma/issues/22228#issuecomment-1844796856, I can trigger an integration release there's a dev version on npm.

**Comment by aqrln** [comment]
@tinola feel free to try `prisma` and `@prisma/client` versions `5.8.0-integration-freebsd14.1` (use an exact version without `^` in package.json)

**Comment by tinola** [comment]
@aqrln, no problems with prisma on FreeBSD 14. Just tested, thank you!

**Comment by aqrln** [comment]
Cool, then this should be good to merge as soon as the conflicts are resolved (sorry, I merged a PR today that probably caused those conflicts) and will be included in the stable 5.8.0 release in January. Thanks for doing the PR and for checking!

**Review by aqrln — APPROVED** [review]

**Review by Jolg42 — APPROVED** [review]

**Pull request merged**
