### PR TITLE
fix: support type inference in webstorm

### LINKED ISSUE #17266: Promise types are not unwrapped properly when using async/await in WebStorm
### Bug description

Return types on PrismaClient are not unwrapped unless you use `foo.then()` manually instead of `await foo` essentially making Prisma unusable in WebStorm.

WebStorm seems to do some custom Promise & async/await handling instead of using the standard TypeScript language service for that.

JetBrains issue: https://youtrack.jetbrains.com/issue/WEB-59004

PR for a hotfix within Prisma:  https://github.com/prisma/prisma/pull/17265

### How to reproduce

1. Check out https://github.com/prisma/prisma-examples
2. Install any of the typescript examples in that repository (with npm, pnpm, yarn, whatever you prefer)
4. Generate the prisma client (e.g. npx prisma generate)
5. Open the example project in webstorm
6. Any of the await'ed returns of any of the functions called on the PrismaClient instance returns the promise still instead of the underlying, unwrapped object

### Expected behavior

They are not unwrapped unless you use foo.then() manually instead of await foo essentially making Prisma unusable in WebStorm.

### Prisma information

Any example from `prisma/prisma-examples` works to reproduce this.

### Environment & setup

IDE: WebStorm or any other JetBrains IDE with TypeScript support

### Prisma Version

4.8.1

### PR DESCRIPTION
**Pull request by fubhy**
For reference: https://youtrack.jetbrains.com/issue/WEB-59004
Fixes: https://github.com/prisma/prisma/issues/17266

### CODE REVIEW

**Review by aqrln — APPROVED** [review]
This looks good to me if it works, but I don't have WebStorm to reproduce the original issue and test these changes. Optimally the bug in WebStorm needs to be fixed upstream, but working around it on our side in the meantime is the right thing to do. Thanks to bringing this to our attention!

**Review by danstarns — APPROVED** [review]

**Comment by fubhy** [comment]
Thanks.

> Optimally the bug in WebStorm needs to be fixed upstream

Agreed. It points at a larger issue somewhere on their side.

**Comment by fubhy** [comment]
> This fix has broken `await` on `PrismaPromise` on VSCode, personally...

Oh, wow, that's odd. I'll debug this later today.

**Comment by aqrln** [comment]
@Tenrys what is the version of VSCode and TypeScript you are using?

**Comment by Tenrys** [comment]
VSCode Version: 1.74.3
TypeScript Version: 4.9.4

**Comment by fubhy** [comment]
@Tenrys I'm sorry but I can't reproduce this.

typescript v4.9.4
prisma v4.9.0
@prisma/client v4.9.0

vscode: 1.74.3

Maybe something with the tsconfig?

These are mine:

```

  "compilerOptions": {
    // Type Checking
    "strict": true,
    // TODO: Consinder enabling this to get stricter checks for explicit `undefined` vs. optional properties.
    // "exactOptionalPropertyTypes": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "useUnknownInCatchVariables": false,
    "noUncheckedIndexedAccess": true,

    // Modules
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "types": ["node", "web"],

    // Emit
    "noEmit": true,
    "declaration": true,
    "declarationMap": true,
    "stripInternal": true,

    // JavaScript Support
    "allowJs": false,
    "checkJs": false,

    // Interop Constraints
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,

    // Language and Environment
    "jsx": "react-jsx",
    "lib": ["ES2022"],
    "target": "ES2022",
    "useDefineForClassFields": true,

    // Completeness
    "skipLibCheck": true // skip all type checks for .d.ts files
  }
  ```

**Comment by Tenrys** [comment]
It still happens even with your `tsconfig`...

I'm gonna try and make a reproduction project at this point.

**Comment by Tenrys** [comment]
So from what I can see, it has to do with my Prisma schema. Just have to narrow down what it is...

**Comment by Tenrys** [comment]
Well, after spending some time... The issue is really dumb. Here is a reproduction repository:

https://github.com/Tenrys/prisma-4.9.0-await-prismapromise-repro/

This PR changed `PrismaPromise` to extend from `Promise`, and if you have a model that is called just that, it will extend from your `Promise` model instead of the native `Promise` object...

It didn't use to be an issue before, somehow. I'll just call my model something different, haha. Might want to prevent something like that from happening though...

**Comment by fubhy** [comment]
That's funny as hell. You must made my day :-D

Not sure what to do about that though. Will leave it to the prisma maintainers from here ;-)

**Comment by janpio** [comment]
Please open a bug report about this - we will want to take a look at it. PR comments are a difficult place to do so. Thanks!

**Comment by ryzencool** [comment]
This problem still exist in webstorm 2022.2.2， my ts version is 5.2.2

**Comment by janpio** [comment]
See my previous comment @ryzencool: https://github.com/prisma/prisma/pull/17265#issuecomment-1397151320

**Pull request merged**
