### PR TITLE
feat(client): add findFirst

### LINKED ISSUE #3676: Implement a `findFirst` API
## Problem
`findOne` is strict in that it requires a unique constraint (@unique, @id) to find a unique entry. That, however, doesn't allow for more flexible kinds of queries which should also usually return a single result.

## Suggested solution
`findFirst`, doing essentially a `findMany` + `take: 1` under the hood.

## Additional context

* https://github.com/prisma/prisma-client-js/issues/232

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes https://github.com/prisma/prisma/issues/3676

### CODE REVIEW

**Comment by Jolg42** [comment]
Looks like we could update the denylist https://github.com/prisma/prisma/blob/ebde14f1f37bee60b9363ee5ff954fd1cbb33f97/src/packages/client/src/generation/generateClient.ts#L520

**Comment by timsuchanek** [comment]
> Looks like we could update the denylist
No need for that, we soon will get rid of most of it ;)

**Comment by bre7** [comment]
Should `take` be part of `FindFirst....Args` ?

**Comment by pantharshit00** [comment]
> Should `take` be part of `FindFirst....Args` ?

This method internally does `take: 1` to limit the result to the first value.

If you need take, use `findMany`

**Comment by bre7** [comment]
I know, my point was...should it ? `findFirst`, as stated in the docs, is sugar for `findMany({ take: 1 })`. Otherwise `findFirst` is an alias of `findMany`.

**Comment by pantharshit00** [comment]
It is not a direct alias. It is implemented on the prisma-engines level as a top level method in the dmmf: https://github.com/prisma/prisma-engines/pull/1132

I think defining it as `directly` findMany take: 1 wouldn't be completely accurate.

It is more like findMany and it flatten out the first result returned by the findMany.

**Pull request merged**
