### PR TITLE
fix(generation): stop stringifying strings

### PR DESCRIPTION
**Pull request by FredericEspiau**
https://github.com/prisma/prisma/blob/main/packages/client/src/generation/TSClient/TSClient.ts#L92 will generate code

# Current behavior

```ts
const root = "/path/to/prisma/";

findSync(root, [
  '"prisma/path/to/schema"',
  '"path/to/schema"',
], ['d'], ['d'], 1)[0] || __dirname
```

will always return `__dirname` even if the path `/path/to/prisma/path/to/schema` exists for example

# New behavior

```ts
const root = "/path/to/prisma/";

findSync(root, [
  'prisma/path/to/schema',
  'path/to/schema",
], ['d'], ['d'], 1)[0] || __dirname
```

will return `/path/to/prisma/path/to/schema`

# Explanation

If a string is given to `JSON.stringify`, it will be wrapped in double quotes

Example: `JSON.stringify("path/to/b") === '"path/to/b"'`

As the path was used in `String.prototype.includes` right there: https://github.com/prisma/prisma/blob/ba74c81fdbc9e6405946fdc6f9d42d103d008dc2/packages/client/src/runtime/utils/find.ts#L41, this would lead to not detecting that the path was a child of the root

Example: `"/usr/path/to/b".includes(JSON.stringify("path/to/b"))" === false`

What you want is `"/usr/path/to/b".includes("path/to/b")" === true`

### CODE REVIEW

**Review by Amirault — APPROVED** [review]

**Comment by millsp** [comment]
Good catch, thank you! We use `JSON.stringify` because it escapes `\` for windows paths.

**Comment by FredericEspiau** [comment]
@millsp ah thank you, I didn't know that, good catch

**Comment by FredericEspiau** [comment]
@millsp as you created this https://github.com/prisma/prisma/pull/8702 should I update my PR or you are taking care of this ?

**Comment by FredericEspiau** [comment]
hey @millsp sorry to bother you again, do you want me to update my PR to use `JSON.stringify` or I shouldn't bother because you will work on https://github.com/prisma/prisma/pull/8702 instead ?

**Comment by millsp** [comment]
No worries @FredericEspiau, I will take your PR from there in a few days. Thanks!

**Comment by FredericEspiau** [comment]
alright thanks !

**Comment by FredericEspiau** [comment]
Oups sorry, I thought you didn't need this anymore 😄

**Comment by FredericEspiau** [comment]
This has been done by https://github.com/prisma/prisma/pull/9295

**Pull request closed without merging**
