### PR TITLE
Small grammar fixes

### PR DESCRIPTION
**Pull request by robin-macpherson**
Some more minor grammar fixes for the docs.

### CODE REVIEW

**Comment by robin-macpherson** [comment]
@nikolasburk Just pasting my response from the other closed PR here in case you didn't see it:

> Thank you @nikolasburk ! Would you mind also merging #4955 ? Also, what's the correct way for me to do this in the future so that I can add you as a reviewer and not have to tag you in a comment?

**Comment by robin-macpherson** [comment]
@do4gr @kuldar @jasonkuhrt @dpetrick is there anyone who can help me merge this PR and why both of my first two PRs got stuck like this? I'll be happy to make sure I do it correctly next time. Please see the above comment and linked PR for context - thank you! 🙇🏻‍♂️

**Comment by nikolasburk** [comment]
Thanks a lot @robin-macpherson! 🙏  Sorry for the delay, this is just a capacity issue at the moment since [we're focusing all our resources on Prisma 2 at the moment](https://github.com/prisma/prisma/issues/4898).

**Comment by robin-macpherson** [comment]
No problem and thank you for helping me on both of these @nikolasburk ! So just to be clear, I did everything correctly and it was just capacity? I was worried that since there were no reviewers added to the PR perhaps nobody had been notified of it.

Keep up the great work with Prisma 2 and thanks for everything!

**Comment by nikolasburk** [comment]
Yes, everything was good from your end! Feel free to keep pinging me on these kinds of PRs, I'm trying to get back as soon as possible! 🙂

**Pull request merged**
