### PR TITLE
chore: rename `EngineTypes` to `BinaryType`

### PR DESCRIPTION
**Pull request by williamluke4**

### CODE REVIEW

**Review by Jolg42 — APPROVED** [review]
It indeed makes it easier to read!

One day we can rename "binary" across the codebase because of Node-API

**Comment by janpio** [comment]
https://github.com/prisma/prisma/issues/7694 might be a place to do that :D

**Comment by Jolg42** [comment]
Checked with Will, and this PR makes the code easier to understand because we had a mix of things before. So it's easier to read/understand & rename after this.

**Comment by janpio** [comment]
So the code is currently consistently referring to what is the `Engine` as the `Binary` and now at least it is consistent?

**Comment by janpio** [comment]
https://github.com/prisma/prisma/issues/7802

**Comment by Jolg42** [comment]
Yes. The gist of this is this https://github.com/prisma/prisma/pull/7791/files#diff-51de7854c0cd4d96d3e28f1415061b8b16734f70d4ed34ba71ff2b79757acd81L35-L41

```diff
-export enum EngineTypes {
+export enum BinaryType {
  queryEngine = 'query-engine',
  libqueryEngineNapi = 'libquery-engine-napi',
  migrationEngine = 'migration-engine',
  introspectionEngine = 'introspection-engine',
  prismaFmt = 'prisma-fmt',
}
```

and EngineType is this

https://github.com/prisma/prisma/blob/6a5729f4fab91d78930c1a8f4b3eecc65600f2b2/src/packages/generator-helper/src/types.ts#L82-L87

**Pull request merged**
