### PR TITLE
fix(sdk): Replaces resolve package by require.resolve

### LINKED ISSUE #8765: `prisma generate` fails in yarn2 / yarn3 workspaces
### Bug description

We are using prisma in a yarn2 monorepo consisting of multiple workspaces. We were on version 2.23.0 before and everything was working fine. After upgrading to 2.29.0, prisma tries to run npm to install `@prisma/client`, even though it's already installed in the current folder. This fails, as npm is unable to recognize the imported workspace.

```sh
yarn prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:core-api-plugins/article-import-edeka

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/valentinmorlock/.npm/_logs/2021-08-16T10_13_58_979Z-debug.log
Error: Command failed with exit code 1: npm install -D prisma@2.29.1
```

### How to reproduce

clone this repo: https://github.com/v-morlock/prisma-yarn2-repro
```
yarn
cd workspace 
yarn prisma generate
```

### Expected behavior

Prisma should generate its files

### Prisma information

-

### Environment & setup

- OS: macOS
- Database: mySQL
- Node.js version: 16.1.0

### Prisma Version

```
2.29.1, stopped working on 2.26.0
```

### PR DESCRIPTION
**Pull request by efernandesng**
Fixes #8765

The problem is that `prisma` creates a bundle, and it bundles the `resolve` dependency. The `resolve` module [doesn't support PnP](https://github.com/browserify/resolve/issues/199), but Yarn patches resolve at install time so that it works with PnP: this doesn't work if `resolve` is inside of a bundle, because Yarn cannot detect it.

To solve that problem, I replaced the package `resolve` with the `require.resolve` keeping the same API (handles the `preserveSymlinks` option).

### CODE REVIEW

**Comment by efernandesng** [comment]
Some CI tests are failing. Not ready for review yet :)

**Comment by Jolg42** [comment]
I converted as a draft so it's clear it's not ready 👍🏼

**Comment by millsp** [comment]
Do you still want to work on this @efernandesng ?

**Comment by efernandesng** [comment]
> Do you still want to work on this @efernandesng ?

Sorry, I don't have much time to finish this PR. I'll close it.

**Pull request closed without merging**
