### PR TITLE
docs: Add Codecov badge to README

### PR DESCRIPTION
**Pull request by thomasrockhu**
Tom from Codecov here. I thought I would go ahead and add the Codecov badge here in case it's useful! Also removed some extra whitespace.

### CODE REVIEW

**Comment by timsuchanek** [comment]
Thanks @thomasrockhu!
The problem is, that right now we don't have codecov configured properly yet, so the reporting is incorrect.
Until then we would not want to merge this, as it's not yet accurately reflecting the current state.

**Comment by thomasrockhu** [comment]
@timsuchanek, got it. Can I do anything to help here?

**Comment by Jolg42** [comment]
@thomasrockhu I noticed strange things on Codecov

I created this issue for now `#4349 Many `Unable to find commit in Github` in commits view`

I didn't create an issue for that, I can see quite big spikes (~ +13%) in coverage chart and it doesn't make sense to me, it doesn't seem accurate. 
Screen Shot 2021-03-05 at 17 29 11

Happy to discuss that in a private channel 😃

**Comment by thomasrockhu** [comment]
@Jolg42, the one thing I noticed on the spikes is that those typically are only uploading coverage reports under the `client` flag like [here](https://codecov.io/gh/prisma/prisma/commit/aa98b48c453ba66393e4d4a68713d5015d0343a4/build) as compared to another [commit](https://codecov.io/gh/prisma/prisma/commit/e969531bfad84d40e2c5e35f29861c0b8735d9bd/build). Is there something in CI that doesn't upload coverage for those paths?

**Comment by Jolg42** [comment]
@thomasrockhu Thanks, it seems that after switching to the GitHub Action (was Bash uploader directly before) and cleaning up the Actions the spikes don't show up anymore 💚 

I'm closing this PR for now as we have some internal homework to do, we'll reopen and merge when ready!

**Comment by thomasrockhu** [comment]
@Jolg42 amazing! I'm glad that that helped. Feel free to let me know if you run into any other issues, or if we can be doing anything better.

**Pull request closed without merging**
