### PR TITLE
fix(generator-helper): missing field types

### PR DESCRIPTION
**Pull request by marcjulian**
* relationFromFields
* isUpdatedAt
* isReadOnly

Example `field` output from a Prisma generator

```json
{
    "name": "user",
    "kind": "object",
    "isList": false,
    "isRequired": true,
    "isUnique": false,
    "isId": false,
    "isReadOnly": false,
    "type": "User",
    "hasDefaultValue": false,
    "relationName": "ProfileToUser",
    "relationFromFields": [
        "userId"
    ],
    "relationToFields": [
        "id"
    ],
    "relationOnDelete": "NONE",
    "isGenerated": false,
    "isUpdatedAt": false
},
```

<details>
<summary>schema.prisma</summary>

```prisma
model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
  role    Role
}

model Profile {
  id     Int     @default(autoincrement()) @id
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

enum Role {
  ADMIN
  USER
}
```
</details>

### CODE REVIEW

**Comment by janpio** [comment]
This only aligns the types to what the code already creates?

**Comment by marcjulian** [comment]
Yes thats what is already created by the generator.

<details>
<summary>For this schema:</summary>

```prisma
model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
  /// user role
  role    Role
}

/// User profile
model Profile {
  id     Int     @default(autoincrement()) @id
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

enum Role {
  /// allowed to do everything
  ADMIN
  USER
}
```
</details>

<details>
<summary>Following datamodel is generated:</summary>

```json
{
  "enums": [
    {
      "name": "Role",
      "values": [
        { "name": "ADMIN", "dbName": null },
        { "name": "USER", "dbName": null }
      ],
      "dbName": null
    }
  ],
  "models": [
    {
      "name": "User",
      "isEmbedded": false,
      "dbName": null,
      "fields": [
        {
          "name": "id",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": true,
          "isReadOnly": false,
          "type": "Int",
          "hasDefaultValue": true,
          "default": { "name": "autoincrement", "args": [] },
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "email",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": true,
          "isId": false,
          "isReadOnly": false,
          "type": "String",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "name",
          "kind": "scalar",
          "isList": false,
          "isRequired": false,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "String",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "posts",
          "kind": "object",
          "isList": true,
          "isRequired": false,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "Post",
          "hasDefaultValue": false,
          "relationName": "PostToUser",
          "relationFromFields": [],
          "relationToFields": [],
          "relationOnDelete": "NONE",
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "profile",
          "kind": "object",
          "isList": false,
          "isRequired": false,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "Profile",
          "hasDefaultValue": false,
          "relationName": "ProfileToUser",
          "relationFromFields": [],
          "relationToFields": [],
          "relationOnDelete": "NONE",
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "role",
          "kind": "enum",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "Role",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false,
          "documentation": "user role"
        }
      ],
      "isGenerated": false,
      "idFields": [],
      "uniqueFields": [],
      "uniqueIndexes": []
    },
    {
      "name": "Profile",
      "isEmbedded": false,
      "dbName": null,
      "fields": [
        {
          "name": "id",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": true,
          "isReadOnly": false,
          "type": "Int",
          "hasDefaultValue": true,
          "default": { "name": "autoincrement", "args": [] },
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "bio",
          "kind": "scalar",
          "isList": false,
          "isRequired": false,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "String",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "user",
          "kind": "object",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "User",
          "hasDefaultValue": false,
          "relationName": "ProfileToUser",
          "relationFromFields": ["userId"],
          "relationToFields": ["id"],
          "relationOnDelete": "NONE",
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "userId",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": true,
          "isId": false,
          "isReadOnly": true,
          "type": "Int",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        }
      ],
      "isGenerated": false,
      "documentation": "User profile",
      "idFields": [],
      "uniqueFields": [],
      "uniqueIndexes": []
    },
    {
      "name": "Post",
      "isEmbedded": false,
      "dbName": null,
      "fields": [
        {
          "name": "id",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": true,
          "isReadOnly": false,
          "type": "Int",
          "hasDefaultValue": true,
          "default": { "name": "autoincrement", "args": [] },
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "title",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "String",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "content",
          "kind": "scalar",
          "isList": false,
          "isRequired": false,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "String",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "published",
          "kind": "scalar",
          "isList": false,
          "isRequired": true,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "Boolean",
          "hasDefaultValue": true,
          "default": false,
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "author",
          "kind": "object",
          "isList": false,
          "isRequired": false,
          "isUnique": false,
          "isId": false,
          "isReadOnly": false,
          "type": "User",
          "hasDefaultValue": false,
          "relationName": "PostToUser",
          "relationFromFields": ["authorId"],
          "relationToFields": ["id"],
          "relationOnDelete": "NONE",
          "isGenerated": false,
          "isUpdatedAt": false
        },
        {
          "name": "authorId",
          "kind": "scalar",
          "isList": false,
          "isRequired": false,
          "isUnique": false,
          "isId": false,
          "isReadOnly": true,
          "type": "Int",
          "hasDefaultValue": false,
          "isGenerated": false,
          "isUpdatedAt": false
        }
      ],
      "isGenerated": false,
      "idFields": [],
      "uniqueFields": [],
      "uniqueIndexes": []
    }
  ]
}
```
</details>

**Comment by Jolg42** [comment]
Looks good to me @timsuchanek

**Comment by benkroeger** [comment]
@timsuchanek @Jolg42 has this somehow been reverted? I'm missing e.g. `isUpdatedAt` and `relationFromFields` in the `Field` [interface](https://github.com/prisma/prisma/blob/master/src/packages/generator-helper/src/dmmf.ts#L71). Generator still produces those props - just missing in the type definition

**Comment by benkroeger** [comment]
I have created #7668 to reintroduce these properties

**Comment by Jolg42** [comment]
Thanks for the PR!

**Pull request merged**
