### PR TITLE
Remove stability limitation docs

### PR DESCRIPTION
**Pull request by PeterDraex**
[Pull request](https://github.com/microsoft/TypeScript/pull/33937) that resolves the only mentioned stability issue has been merged, so let's remove stability issues from the docs.

### CODE REVIEW

**Comment by janpio** [comment]
Thanks @PeterDraex, I requested reviews from the people that should know if this is actually already resolved or if we have to wait for something to be released first.

**Comment by PeterDraex** [comment]
Microsoft is planning to release Typescript 3.7 on November 5.
https://github.com/microsoft/TypeScript/issues/33352

**Review by nikolasburk — APPROVED** [review]
Personally I wasn't aware that the "stability" issues we mentioned in our limitations were due to one specific issue but I had rather interpreted them as a general "word of warning" that things _might_ break and therefore production-usage is not recommended. 

However, I think we've come to a point where the preview is mature/stable enough to not list stability as one of the core limitations any more, so I'd be fine with merging it.

**Comment by PeterDraex** [comment]
Typescript 3.7 has been released today.

**Comment by timsuchanek** [comment]
Thanks again @PeterDraex for the PR!

**Pull request merged**
