### PR TITLE
fix(cli): fix debounce for `prisma generate --watch` command

### PR DESCRIPTION
**Pull request by Gnucki**
Fix for issue #13677

### CODE REVIEW

**Comment by SevInf** [comment]
@Gnucki thanks for the pull request.
Change looks good to me. Could you sign  the CLA so we could merge it?

**Comment by Gnucki** [comment]
> @Gnucki thanks for the pull request. Change looks good to me. Could you sign the CLA so we could merge it?

I did it, but the status don't show it.

**Comment by janpio** [comment]
The commit is attributed to a user with your name directly, possibly with a different or no email address. That makes it impossible for the CLA tool to pick up unfortunately.

**Comment by Gnucki** [comment]
OK, sorry ! First time I use that kind of tool. This should be good, now.

**Comment by janpio** [comment]
Nothing to be sorry about, it is quite a pain - even internally - but legally required sometimes 🤷 Thanks for fixing this!

**Review by aqrln — APPROVED** [review]

**Pull request merged**
