### PR TITLE
ci: Windows -RunAsAdmin

### PR DESCRIPTION
**Pull request by Jolg42**
Main currently failing with https://github.com/prisma/prisma/runs/5481573468?check_suite_focus=true
```
Run bash .github/workflows/setup-mysql.sh
+ '[' Windows = Windows ']'
+ pwsh .github/workflows/install-mysql.ps1
Initializing...
Running the installer as administrator is disabled by default, use -RunAsAdmin parameter if you know what you are doing.
Abort.
Error: Process completed with exit code 1.
```

### CODE REVIEW

**Review by aqrln — APPROVED** [review]
Unexpected breaking change from scoop 😄
Thank you!

**Comment by Jolg42** [comment]
Indeed!

**Comment by janpio** [comment]
It should not really be necessary for Scoop to run as Admin though. That is why they discourage that and make you supply an additional parameter.

**Comment by aqrln** [comment]
@janpio yes, but the user on GitHub Actions is a full Admin with UAC disabled, we don't get to choose that

**Comment by janpio** [comment]
Yeah, turns out that is indeed a change on Scoop side somehow - also affected engines: https://github.com/prisma/prisma-engines/pull/2755

**Pull request merged**
