### PR TITLE
fix: correct "setup" to "set up" when used as a verb

### PR DESCRIPTION
**Pull request by DePasqualeOrg**
"setup" is a noun, and "set up" is a verb. Previously "setup" was used incorrectly as a verb.

### CODE REVIEW

**Review by aqrln — APPROVED** [review]
Thank you!

**Comment by janpio** [comment]
That rebase action does not seem to work with forks :/ (And generally did not achieve what I was hoping last Friday...)

The "Update branch" button on GH UI might do what it should though @aqrln

**Comment by aqrln** [comment]
Added @zachtil to reviewers as per the conversation with @tanberry and him

**Pull request merged**
