### PR TITLE
fix: update esbuild

### PR DESCRIPTION
**Pull request by timsuchanek**
Might do the trick for https://github.com/prisma/prisma/issues/6051

### CODE REVIEW

**Comment by Jolg42** [comment]
Did it help? Should we merge?

**Comment by timsuchanek** [comment]
@Jolg42 once I have news, I'll post them here

**Comment by timsuchanek** [comment]
This fixed the `debugLib is not a function` error now, but not yet the missing binary.

**Comment by Jolg42** [comment]
Actually Renovate updated it again https://github.com/prisma/prisma/pull/6325 so we need to fix it again and disable renovate for esbuild

**Pull request merged**
