### PR TITLE
test(client/debug): switch from ts-jest to swc

### PR DESCRIPTION
**Pull request by Jolg42**
Follows https://github.com/prisma/prisma/pull/11848

### CODE REVIEW

**Comment by Jolg42** [comment]
Let's see if anything breaks

**Comment by Jolg42** [comment]
swc added in https://github.com/prisma/prisma/pull/12560

**Comment by aqrln** [comment]
@Jolg42 should this be closed now?

**Comment by Jolg42** [comment]
@aqrln Let's close because it's old though `@prisma/debug` package is not yet using SWC and this was about that.

**Pull request closed without merging**
