### PR TITLE
chore: migrate driver adapters from prisma/prisma-engines

### PR DESCRIPTION
**Pull request by miguelff**
Sibling to https://github.com/prisma/prisma-engines/pull/4380 (merge this PR first, then the engines' one)

Summary of changes:
* Oldest 66 commits corresponds to the prisma-engines history of the driver adapters folder
* Then we (@SevInf and I paired on this) making the `adapter-*` and `driver-adapters-util` modules packages of the prisma/prisma monorepository worskpace
* We tweaked dependencies to point to the workspace and build from source
* We didn't migrate tsconfig, but replicated the tsconfig used in prisma engines in here
* We removed smoke tests because they cease to make sense now

In order to merge this, we need tests passing on https://github.com/prisma/prisma-engines/pull/4380
The publishing story will work as with other packages in the monorepo, i.e. using the same versioning conventions.

---

From https://github.com/prisma/prisma-engines/pull/4380:

> so the order of merging PRs that span both codebases is:
> First merge changes in prisma/prisma
> Then merge changes in prisma-engines

### CODE REVIEW

**Comment by miguelff** [comment]
This is ready to be reviewed.

**Comment by jkomyno** [comment]
From https://github.com/prisma/prisma-engines/pull/4380:

> so the order of merging PRs that span both codebases is:
> First merge changes in prisma/prisma
> Then merge changes in prisma-engines

**Comment by Jolg42** [comment]
I'm still reviewing but for now
@miguelff you need to remove these 2 pieces of code https://github.com/prisma/prisma/blob/543793ebb8a38d3c2fd92be06986519c839a2907/.github/workflows/release-latest.yml#L86-L96
https://github.com/prisma/prisma/blob/543793ebb8a38d3c2fd92be06986519c839a2907/.github/workflows/release-ci.yml#L84-L94

**Review by jkomyno — APPROVED** [review]

**Comment by Jolg42** [comment]
This could be removed from Renovate now or after
https://github.com/prisma/prisma/blob/6f29d51d1f2cc4298bc7373c015e270ac57c2dd6/.github/renovate.json#L21-L26

**Comment by jkomyno** [comment]
Note: lint tests are failing.

**Review by millsp — APPROVED** [review]

**Comment by janpio** [comment]
@millsp is on that in a follow up PR I think.

**Comment by Jolg42** [comment]
Yes, this will be fixed in https://github.com/prisma/prisma/pull/21642

**Pull request merged**
