### PR TITLE
feat(client): add esm support

### LINKED ISSUE #5030: Support ES6 modules export
It would be great if the Prisma Client JS generator would be compatible with ES6 modules out of the box.

Note: Related to prisma/prisma-client-js#175

### PR DESCRIPTION
**Pull request by muxahuk**
This is attempt to make esm support when executing "prisma generate" so that when user uses ESM he do not have to do:
```
import pkg from '@prisma/client';
const { PrismaClient } = pkg;
```
and can use:
```
import { PrismaClient } from '@prisma/client';
```
instead
This patch fixes the issue when using ESM:
Named export 'PrismaClient' not found. The requested module '@prisma/client' is a CommonJS module, which may not support all module.exports as named exports.

Closes https://github.com/prisma/prisma-client-js/issues/539

### CODE REVIEW

**Comment by muxahuk** [comment]
Not exectly what i wanted to do.. i wanted to create a pull request to my copied repo.. but since this is here - i do not insist so that this goes in or u accept the MR.

I was playing around with ESM modules in node and with typegraphql-prisma. So i was generating my source to ESM and then there was annoying error:
Named export 'PrismaClient' not found. The requested module '@prisma/client' is a CommonJS module, which may not support all module.exports as named exports.

exploring what it is i figured out that i don't want to do what they suggest:
```
import pkg from '@prisma/client';
const { PrismaClient } = pkg;
```
and instead i want to use it normally like:
`import { PrismaClient } from '@prisma/client';`

so i went and made a change in ur client library to support ESM...

**Comment by timsuchanek** [comment]
Thanks for the PR! We can take that over from here. Can you please sign the CLA? You can do that by clicking on the CLA button.

**Comment by muxahuk** [comment]
> Thanks for the PR! We can take that over from here. Can you please sign the CLA? You can do that by clicking on the CLA button.

Cool!
Signed.

I guess build fails bcs. it can't create runtime/esm folder.. should be straight forward to fix that - add creation of runtime folder before runtime/esm :)

**Comment by timsuchanek** [comment]
Update: https://github.com/prisma/prisma/pull/4265#issuecomment-728133393

**Comment by anonrig** [comment]
hey @timsuchanek are there are updates on this?

**Comment by timsuchanek** [comment]
Closing in favor of https://github.com/prisma/prisma/pull/4265

**Pull request closed without merging**
