### PR TITLE
fix(client): support list defaults in DMMF types

### PR DESCRIPTION
**Pull request by aqrln**
Ref: https://github.com/prisma/prisma/issues/13321
Ref: https://github.com/prisma/prisma-engines/pull/2946
Ref: https://github.com/prisma/prisma/pull/13912
Ref: https://github.com/prisma/prisma/pull/13934

### CODE REVIEW

**Review by SevInf — APPROVED** [review]

**Review by millsp — APPROVED** [review]
Can you please create an issue so that we can add tests for this later if we don't have the time to do it now?

**Comment by aqrln** [comment]
@millsp 

> Can you please create an issue so that we can add tests for this later if we don't have the time to do it now?

Sure! Do you see anything else that needs to be tested on the client side here btw (except the `exhaustive-schema` test updated in this PR)? I think what's probably missing is an introspection test in `packages/migrate`, but that would be an issue for the Schema Team then.

**Comment by millsp** [comment]
I think that we should have basic queries on lists like filtering, and setting values. That would be similar to what we've done in mongo composites. See the new input types:
* https://github.com/prisma/prisma/pull/13984/files#diff-5ad6f4abad4b644d8dd981d5de9d33c198f960f78733482a7021c420174c4d7dR20291-R20295
* https://github.com/prisma/prisma/pull/13984/files#diff-5ad6f4abad4b644d8dd981d5de9d33c198f960f78733482a7021c420174c4d7dR19788-R19794

**Comment by aqrln** [comment]
I took a quick look, and

> * https://github.com/prisma/prisma/pull/13984/files#diff-5ad6f4abad4b644d8dd981d5de9d33c198f960f78733482a7021c420174c4d7dR20291-R20295

I don't see any tests for this.

> * https://github.com/prisma/prisma/pull/13984/files#diff-5ad6f4abad4b644d8dd981d5de9d33c198f960f78733482a7021c420174c4d7dR19788-R19794

This is tested in `packages/client/src/__tests__/integration/happy/scalar-list`

**Comment by aqrln** [comment]
https://github.com/prisma/prisma/issues/13996

**Comment by millsp** [comment]
Thank you :100:

**Pull request merged**
