### PR TITLE
chore: remove unused script

### PR DESCRIPTION
**Pull request by psavan1655**
style: Removed console log. As i suppose developer forgot to delete after testing it.

### CODE REVIEW

**Comment by Jolg42** [comment]
@psavan1655 The console.log is valid here because it's a manual script so I won't merge this.

Though If you want to edit this PR and actually delete this script that would be nice since it's not used and could be cleaned up.

**Comment by psavan1655** [comment]
> @psavan1655 The console.log is valid here because it's a manual script so I won't merge this.
> 
> Though If you want to edit this PR and actually delete this script that would be nice since it's not used and could be cleaned up.

You mean i can delete the whole file? Please correct me if i am wrong. As it is my first PR to open source. And thankyou for a wonderful response.

**Comment by Jolg42** [comment]
Yes indeed, deleting the whole file would be nice!

**Comment by psavan1655** [comment]
> Yes indeed, deleting the whole file would be nice!

I have deleted the file.

**Review by Jolg42 — APPROVED** [review]
Thanks for your first PR!

**Pull request merged**
