### PR TITLE
chore(instrumentation): Update OpenTelemetry dependencies to remove deprecation warning

### PR DESCRIPTION
**Pull request by unflxw**
Updating `@opentelemetry/instrumentation` to `0.34.0` removes `@opentelemetry/api-metrics` as a dependency, therefore removing the deprecation warning about it when running `npm install`.

The deprecation warning says to use `@opentelemetry/api` version `1.3.0` or greater, so use that instead.
https://www.npmjs.com/package/@opentelemetry/api-metrics
Screenshot 2023-01-09 at 13 00 11

### CODE REVIEW

**Comment by Jolg42** [comment]
It would make sense to also update the version in the other packages (engine-core & client)
https://github.com/search?q=repo%3Aprisma%2Fprisma+OpenTelemetry+language%3AJSON&type=code&l=JSON

**Comment by unflxw** [comment]
@Jolg42 Thanks for the quick review! Done and done. In the process I ended up updating other dependencies as to avoid peer dependency issues.

**Review by Jolg42 — APPROVED** [review]
Thank you, @unflxw, for your first PR here 💚 
This looks great to me, I just asked @danstarns to review as well

**Review by danstarns — APPROVED** [review]
Nice work, thanks for this. Looks good to me and all tests passing! Cheers

**Comment by unflxw** [comment]
Thanks y'all @danstarns @Jolg42! And thanks for all the quality work on Prisma and the OpenTelemetry instrumentation! It's great to see a library where OpenTelemetry support is built-in instead of monkey-patched on top.

**Pull request merged**
