### PR TITLE
perf(cli): CLI startup time improvement

### PR DESCRIPTION
**Pull request by yehonatanz**
Gains according when running `time yarn prisma` with no other arguments on a medium sized monorepo at my company: (on my Intel 2019 MacBook Pro)
- When `CHECKPOINT_DISABLE=1`: 8s -> 2s
- When checkpoint is enabled: 8s -> 3.6s

We love prisma and would be very happy to have our CLI load a little faster 😊

### CODE REVIEW

**Comment by yehonatanz** [comment]
Hey @SevInf is there anything I should do to move this forward?

**Comment by Jolg42** [comment]
@yehonatanz Thanks for this PR, we want to review this very soon.
But we need to balance some priorities, we are releasing 5.12.0 today for example.
I don't think we need anything else for now.

**Review by Jolg42 — APPROVED** [review]

**Comment by Jolg42** [comment]
@yehonatanz I added some performance measurements that looked interesting to me.
I think the latency comes from `await checkpoint.check(data)` here.
I could not reproduce with a big difference you mentioned though.
Now, I will merge this and once it is available as a dev version, I'll let you know so you can try this, I'm curious to see the debug logs for your project when the env var is not set.

**Comment by yehonatanz** [comment]
> @yehonatanz I added some performance measurements that looked interesting to me. I think the latency comes from `await checkpoint.check(data)` here. I could not reproduce with a big difference you mentioned though. Now, I will merge this and once it is available as a dev version, I'll let you know so you can try this, I'm curious to see the debug logs for your project when the env var is not set.

Sure thing, I'll get those on Monday

**Comment by Jolg42** [comment]
@yehonatanz You can try this
```
DEBUG=prisma* npx prisma@5.13.0-dev.13 -v
```

**Comment by yehonatanz** [comment]
@Jolg42 , as promised:

With `CHECKPOINT_DISABLE=1`:
```
prisma:engines binaries to download libquery-engine, schema-engine +215ms
prisma:loadEnv project root found at <PROJECT_DIR>/package.json +439ms
prisma:tryLoadEnv Environment variables not found at null +1ms
prisma:tryLoadEnv Environment variables not found at undefined +0ms
prisma:tryLoadEnv No Environment variables loaded +0ms
prisma:getConfig Using getConfig Wasm +29ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +9ms
prisma:cli:bin Execution time for executing "await cli.parse(commandArray)": 258.44388580322266 ms +1ms
prisma:cli:checkpoint runCheckpointClientCheck() is disabled by the CHECKPOINT_DISABLE env var. +0ms

4.04s user 0.47s system 135% cpu 3.320 total
```

Without:
```
prisma:engines binaries to download libquery-engine, schema-engine +208ms
prisma:loadEnv project root found at <PROJECT_DIR>/package.json +448ms
prisma:tryLoadEnv Environment variables not found at null +2ms
prisma:tryLoadEnv Environment variables not found at undefined +0ms
prisma:tryLoadEnv No Environment variables loaded +0ms
prisma:getConfig Using getConfig Wasm +28ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +9ms
prisma:cli:bin Execution time for executing "await cli.parse(commandArray)": 276.2214665412903 ms +1ms
prisma:getConfig Using getConfig Wasm +2ms
prisma:getConfig config data retrieved without errors in getConfig Wasm +1ms
prisma:cli:checkpoint runCheckpointClientCheck(): Execution time for getting info: 3.022378921508789 ms +0ms
prisma:cli:checkpoint runCheckpointClientCheck(): Execution time for "await checkpoint.check(data)": 20.147640705108643 ms +21ms

4.03s user 0.49s system 136% cpu 3.320 total
```

Might worth mentioning that we use yarn zero-installs so `pnpify` is needed to execute the prisma CLI and probably incurs its own overhead

**Pull request merged**
