### PR TITLE
fix(client): add missing actions to Prisma action type

### LINKED ISSUE #15444: PrismaAction type out of date
### Bug description

The exported type `PrismaAction` referenced by `MiddlewareParams` is missing the new new `findFirstOrThrow` and `findUniqueOrThrow` actions from the 4.0 release.

### How to reproduce

Build the client

### Expected behavior

```
type MissingdActions = "findFirstOrThrow" | "findUniqueOrThrow"
type TotalActions = Prisma.MiddlewareParams & MissingActions
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
import { Prisma, PrismaClient } from "@prisma/client"
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.16.0

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
```

### LINKED ISSUE #17470: `Type '"findUniqueOrThrow"' is not assignable to type 'PrismaAction'`
### Bug description

Hey Guys,

I'm using the `Prisma.MiddlewareParams` type which contains an attribute `action` of type [PrismaAction](https://github.com/prisma/prisma/blob/731dce39919db180795fd923202a46d5ae833562/packages/client/src/generation/TSClient/PrismaClient.ts#L594-L610). Which is missing a couple of actions that actually exists `findUniqueOrThrow` and `findFirstOrThrow`

Because of that we get a ts error when using one of those missing types:
Screen Shot 2023-01-22 at 19 32 25

### How to reproduce

Just add this code in a ts file and you'll see the error
```typescript
  const action : Prisma.PrismaAction = 'findUniqueOrThrow';
  console.log(action);
```

### Expected behavior

There shouldn't be a ts error because those actions do exists.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db" // env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}


model Planet {
  id        Int     @id @default(autoincrement())  
  name      String  
  diameter  String
  gravity   String
  terrain   String
  createdAt DateTime
  updatedAt DateTime?
  deletedAt DateTime?
}

```

```ts
import { Prisma } from '@prisma/client';

  const action : Prisma.PrismaAction = 'findUniqueOrThrow';
  console.log(action);
```

### Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: v16.14.0

### Prisma Version

```
 "@prisma/client": "^4.7.1",
```

### PR DESCRIPTION
**Pull request by mejiaej**
I'm adding missing `findUniqueOrThrow` and `findFirstOrThrow` to PrismaAction ts type.

Closes #17470
Closes #15444

### CODE REVIEW

**Comment by jhonkitkaton** [comment]
What happened with this bug? Is there already a solution or alternative to be able to control this action in the middleware?

**Comment by shadoath** [comment]
What do we need to do for it to pass docker client checks?

**Comment by Jolg42** [comment]
This looks good to me, what do you think @SevInf / @aqrln / @millsp ?

**Review by aqrln — APPROVED** [review]
This looks good to me! I've updated the branch and the snapshots in tests (since now they're split by the engine/runtime type).

**Pull request merged**
