### PR TITLE
Integration tests for SQLite and MySQL

### LINKED ISSUE #1602: Integration tests: MySQL
Right now we just have postgres

### LINKED ISSUE #1603: Integration tests: SQLite
Right now we just have postgres

### PR DESCRIPTION
**Pull request by Jolg42**
Issues
https://github.com/prisma/prisma2/issues/1603
https://github.com/prisma/prisma2/issues/1602

SQLite: ready but each test is slow and takes 3s
MySQL: ready!

### CODE REVIEW

**Comment by matthewmueller** [comment]
🙌 🙌 🙌 🙌 🙌 🙌

**Comment by Jolg42** [comment]
@matthewmueller We really need to name these tests one day, do you think you could help with that?

**Comment by matthewmueller** [comment]
For my understanding, do these tests line up exactly? I'm wondering if we should stick all the database in the same file, so they don't drift.

**Comment by Jolg42** [comment]
@matthewmueller We may want to reorganize the architecture at some point, right now they are copies so they follow the same order.

**Pull request merged**
