### PR TITLE
tests: add tests for issue #14539 (not reproducible at the moment)

### PR DESCRIPTION
**Pull request by jkomyno**
Reproduction tests for https://github.com/prisma/prisma/issues/14539.
Currently, the issue cannot be reproduced, even when using `prisma@4.1.1` explicitly.

## Run Tests

- Run `docker-compose -f docker/docker-compose.yml up` (you can comment out all services but `mariadb`)
- Define the env variable `TEST_FUNCTIONAL_MARIADB_URI=mysql://root:root@localhost:4306/PRISMA_DB_NAME`
- in `./packages/client`, run `pnpm run test:functional gh-14539/tests.ts`

### CODE REVIEW

**Comment by janpio** [comment]
When following these instructions:
```
 FAIL  tests/functional/gh-14539/tests.ts
  ● gh-14539 (provider=mysql) › issue #14539 › findMany + include without creating anything first

    Required env variable TEST_FUNCTIONAL_MYSQL_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions
```

**Comment by janpio** [comment]
After setting `export TEST_FUNCTIONAL_MYSQL_URI="mysql://root:root@localhost:3306/PRISMA_DB_NAME"` as well:

```
gitpod /workspace/prisma/packages/client (test/reprod-issue-14539) $ pnpm run test:functional gh-14539/tests.ts

> @prisma/client@0.0.0 test:functional /workspace/prisma/packages/client
> node -r esbuild-register helpers/functional-test/run-tests.ts "gh-14539/tests.ts"

 PASS  tests/functional/gh-14539/tests.ts (15.715 s)
  gh-14539 (provider=mysql)
    issue #14539
      ✓ findMany + include without creating anything first (90 ms)
      ✓ $queryRaw + IN after creating few elements (15 ms)
      ✓ $queryRaw + IN after creating 1000+ elements (637 ms)
      ✓ findMany + IN after creating few elements (18 ms)
      ✓ findMany + IN after creating at least 1000 random elements (3014 ms)
      ✓ findMany + include after creating few elements (44 ms)
      ✓ findMany + include after creating 1000+ elements (8316 ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        15.758 s, estimated 17 s
Ran all test suites matching /gh-14539\/tests.ts/i.
 FAIL  tests/functional/typescript/tests.ts (9.405 s)
  typescript
    ✕ gh-14539 (provider=mysql)/tests.ts (7 ms)
    ✓ globals.d.ts

  ● typescript › gh-14539 (provider=mysql)/tests.ts

    assert.fail(received, expected)

    Message:
      Object is of type 'unknown'.
    at (tests/functional/gh-14539/.generated/gh-14539 (provider=mysql)/tests.ts:107:16)

      56 |     for (const checkPath of keys(suiteChecks)) {
      57 |       if (checkPath.includes(path.dirname(suiteFilePath))) {
    > 58 |         assert.fail(suiteChecks[checkPath])
         |                ^
      59 |       }
      60 |     }
      61 |   })

      at fail (typescript/tests.ts:58:16)
          at runMicrotasks (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        9.446 s, estimated 13 s
Ran all test suites matching /typescript/i.
 ELIFECYCLE  Command failed with exit code 1.
 ```
 
 Not sure if this is what we want to see or the opposite.

**Comment by jkomyno** [comment]
> When following these instructions:
> 
> ```
>  FAIL  tests/functional/gh-14539/tests.ts
>   ● gh-14539 (provider=mysql) › issue #14539 › findMany + include without creating anything first
> 
>     Required env variable TEST_FUNCTIONAL_MYSQL_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions
> ```

Yeah, I've noticed this failing on the CI, even though `TEST_FUNCTIONAL_MYSQL_URI` is defined [here](https://github.com/prisma/prisma/blob/6c2670bc0e7945406a52a4e1ca4b4b54cc9b3e0d/.github/workflows/test.yml#L188) and the schema points to `TEST_FUNCTIONAL_MARIADB_URI`, which is also defined [here](https://github.com/prisma/prisma/blob/6c2670bc0e7945406a52a4e1ca4b4b54cc9b3e0d/.github/workflows/test.yml#L189).

The `no-docker` tests are expected to fail on the CI, at least at the moment.

**Comment by jkomyno** [comment]
> 

The first series of tests running is the relevant part:

```
    issue #14539
      ✓ findMany + include without creating anything first (90 ms)
      ✓ $queryRaw + IN after creating few elements (15 ms)
      ✓ $queryRaw + IN after creating 1000+ elements (637 ms)
      ✓ findMany + IN after creating few elements (18 ms)
      ✓ findMany + IN after creating at least 1000 random elements (3014 ms)
      ✓ findMany + include after creating few elements (44 ms)
      ✓ findMany + include after creating 1000+ elements (8316 ms)
```

The typings indeed seem to fail atm, that's going to be a question for Serhii tomorrow.

**Comment by janpio** [comment]
(I ran your instructions via Gitpod, just to confirm your description)

**Comment by kkomelin** [comment]
Hi guys,

The topic starter here, ready to collaborate. Any questions. please welcome.

Thank you very much for working on this issue! I appreciate it.

I've compared your test cases with my code and noticed a couple of differences:

### 1. Including posts as well

**Yours:**
```javascript
const posts = await prisma.post.findMany({
  include: {
    tags: {
      include: {
        tag: true,
        post: true,
      },
    },
  },
})
```

**Mine:**
```javascript
const posts = await prisma.post.findMany({
    include: {
      tags: {
        include: {
          tag: true,
        },
      },
    },
  })
```
As you may see, I don't include the posts itself because we already refer to prisma.post which should return posts anyway. At least I think it should. Can it affect the result somehow?

### 2. Unique ids

You used Set to make the random ids unique and I didn't:

**Yours:**
```javascript
const randomIds = [...new Set(Array.from({ length: 5000 }, () => Math.floor(Math.random() * 5000)))]
```

This one returns results as expected.

**Mine:**
```javascript
const randomIds = Array.from({ length: 5000 }, () => Math.floor(Math.random() * 5000)))
```

This one causes the result of the IN query be an empty array. 
**Hooray! We have identified the reason of the issue! Thanks to your tests!**

This is also actual for Prisma version is 4.2.1.
I've reproduced the IN issue with 4.2.1 but couldn't reproduce the relation queries issue there though.

Could you please create a test case for not unique IDs passed to IN? Because it's valid query for Mysql. A query like the following will return a correct result and not an empty set:

```sql
SELECT * FROM tags WHERE id IN (76,76)
```

**Comment by kkomelin** [comment]
Not sure if fixing this will solve all the problems but at least it's a good step forward.

**Comment by kkomelin** [comment]
What a tricky bug!

```javascript
  const tags = await prisma.tag.findMany({
    where: {
      id: {
        in: [... new Set(Array.from({ length: 5000 }, () => Math.floor(Math.random() * 5000)))]
      }
    }
  })
  ```
 This query returns an empty array `[]`, so I have to conclude that that 1000 number is also involved somehow.
 
 Prisma 4.2.1

**Comment by kkomelin** [comment]
Reproduced the issue in Prisma 4.3.0

**Comment by jkomyno** [comment]
> Hi guys,
> 
> The topic starter here, ready to collaborate. Any questions. please welcome.
> 
> Thank you very much for working on this issue! I appreciate it.
> 
> I've compared your test cases with my code and noticed a couple of differences:
> 
> ### 1. Including posts as well
> **Yours:**
> 
> ```js
> const posts = await prisma.post.findMany({
>   include: {
>     tags: {
>       include: {
>         tag: true,
>         post: true,
>       },
>     },
>   },
> })
> ```
> 
> **Mine:**
> 
> ```js
> const posts = await prisma.post.findMany({
>     include: {
>       tags: {
>         include: {
>           tag: true,
>         },
>       },
>     },
>   })
> ```
> 
> As you may see, I don't include the posts themselves because we already refer to `prisma.post` which should return posts anyway. At least I think it should. Can it affect the result somehow?
> 
> ### 2. Unique ids
> You used `Set` to make the random ids unique and I didn't:
> 
> **Yours:**
> 
> ```js
> const randomIds = [...new Set(Array.from({ length: 5000 }, () => Math.floor(Math.random() * 5000)))]
> ```
> 
> This one returns correct results.
> 
> **Mine:**
> 
> ```js
> const randomIds = Array.from({ length: 5000 }, () => Math.floor(Math.random() * 5000)))
> ```
> 
> This one causes the result of the IN query to be an empty array. **Hooray! We have identified the reason of the issue! Thanks to your tests!**
> 
> This is also actual for Prisma version is 4.2.1. I've reproduced the IN issue with 4.2.1 but couldn't reproduce the relation queries issue there though.
> 
> Could you please create a test case for not unique IDs passed to IN? Because it's a valid query for Mysql. A query like the following returns the correct result and not an empty set:
> 
> ```sql
> SELECT * FROM tags WHERE id IN (76,76)
> ```

Thank you for your comment!

1. We added the additional `post` in `include` hoping it'd trigger the issue, but both "yours" and "mine" successfully resolve when querying e.g. 5000 posts with 2 tags each. However, I have just tried a test with 1000 posts with 1000 tags each, and that indeed fails silently as your issue stated.

2. I had actually attempted both versions, one with distinct random ids, and one with random ids with potential duplicates.
I'm currently testing the following and still cannot reproduce the issue (I obtain two equivalent arrays with about ~3000 entries each):

```ts
import assert from 'node:assert/strict'
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function createTags(length: number): Promise<number[]> {
  const ids = Array.from({ length }, (_, i) => i + 1)

  const prismaPromises: any = []
  for (const id of ids) {
    prismaPromises.push(
      prisma.tag.create({
        data: {
          id,
        },
      }),
    )
  }

  await prisma.$transaction(prismaPromises)
  return ids
}

async function main() {
  await createTags(5000)
  const randomIds = Array.from({ length: 5000 }, () => Math.floor(Math.random() * 5000))
  const distinctRandomIds = [...new Set(randomIds)]
 
  console.log('randomIds length', randomIds.length) // 5000
  console.log('uniqueRandomIds length', uniqueRandomIds.length) // ~3000

  const tagsFromRandomIds = await prisma.tag.findMany({
    where: {
      id: { in: randomIds },
    },
  })

  const tagsFromDistinctRandomIds = await prisma.tag.findMany({
    where: {
      id: { in: distinctRandomIds },
    },
  })

  console.log('tagsFromRandomIds\n', tagsFromRandomIds) // array with ~3000 entries
  console.log('tagsFromDistinctRandomIds\n', tagsFromDistinctRandomIds) // array with ~3000 entries

  assert.equal(distinctRandomIds.length > 2900, true)
  assert.equal(distinctRandomIds.length, tagsFromRandomIds.length)
  assert.equal(tagsFromRandomIds.length, tagsFromDistinctRandomIds.length)
  assert.deepEqual(tagsFromRandomIds, tagsFromDistinctRandomIds)
}
```

Could you please paste your complete test as a comment here? (with creation + selection)

**Comment by kkomelin** [comment]
> However, I have just tried a test with 1000 posts with 1000 tags each, and that indeed fails silently as your issue stated.

That's a good sign. Then something is not correct.

> Could you please paste your complete test as a comment here? (with creation + selection)

Unfortunately, I can't past full code here. It's a real production app with user-generated content and many fields including confidential. But I run all of my snippets from the app and reproduce the issue. 

Do you have a starter template project which I can use to try to simulate the issue?

**Comment by kkomelin** [comment]
I have run your snipped from my app and here is what I received:

```
randomIds length 5000
uniqueRandomIds length 3217
tagsFromRandomIds
 []
tagsFromDistinctRandomIds
 []
received error AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

3217 !== 0

    at .../scripts/bug.ts:49:10
    at Generator.next (<anonymous>)
    at fulfilled (.../scripts/bug.ts:5:58) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 3217,
  expected: 0,
  operator: 'strictEqual'
}
error Command failed with exit code 1.
```

**Comment by kkomelin** [comment]
If it helps here is the table structure. Let's test your snippet in isolation without any relations or other tables. I will now remove all other tables from prisma conf.

```sql
CREATE TABLE `tags` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(191) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`path` VARCHAR(191) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`type` ENUM('STANDARD','MARKETCAP') NOT NULL DEFAULT 'STANDARD' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `tags_name_key` (`name`) USING BTREE,
	INDEX `tags_path_idx` (`path`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;
```

```prisma
model Tag {
  id                      Int             @id @default(autoincrement()) @db.UnsignedInt
  name                    String          @unique
  path                    String
  type                    TagType         @default(STANDARD)

  @@index([path])

  @@map("tags")
}

enum TagType {
  STANDARD
  MARKETCAP
}
```

**Comment by kkomelin** [comment]
The same issue with only one table in the database `tags`. Will now create a github repo for you to reproduce it.

**Comment by jkomyno** [comment]
Thank you @kkomelin. In general, the smaller the schema (and the resulting table), the easier the reproduction.
Hopefully that will be enough to arrive at a mutual understanding of how to trigger the issue, but please keep in mind that we're able to sign NDAs for confidentiality, should that be needed.

**Comment by kkomelin** [comment]
Thanks @jkomyno I will do my best to isolate the context of the issue. And I get some results already. Please give me a few mins to compose a new github project with reproduction of the issue in maximum isolation

**Comment by jkomyno** [comment]
> Thanks @jkomyno I will do my best to isolate the context of the issue. And I've gotten some results already. Please give me a few mins to compose a new github project with reproduction of the issue in maximum isolation

That's great, thanks again. I'm clustering all similar issues I'm finding [in this thread](https://github.com/prisma/prisma/issues/14539#issuecomment-1234052246). Hopefully, some of the existing comments by other users may be helpful for your reproduction.

**Comment by kkomelin** [comment]
@jkomyno Here is a totally isolated environment that reproduces the bug https://github.com/kkomelin/prisma-in-issue-reproduction

**Comment by kkomelin** [comment]
As suggested https://github.com/prisma/prisma/issues/12338#issuecomment-1195954336, I have tried to switch to Mariadb 10.7.5. Got better results but for some reasons the assertion in your script is not identical:

```
received error AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

3187 !== 3186

    at /srv/sites/my/tmp/prisma-in-issue-reproduction/script.ts:53:10
    at Generator.next (<anonymous>)
    at fulfilled (/srv/sites/my/tmp/prisma-in-issue-reproduction/script.ts:5:58) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 3187,
  expected: 3186,
  operator: 'strictEqual'
}
```

**Comment by kkomelin** [comment]
And yes, it's a combination of Prisma + MariaDB < 10.7.4

**Comment by jkomyno** [comment]
Thank you so much @kkomelin! I have simplified the reproduction as follows:

```typescript
// prisma/schema.prisma

**Comment by kkomelin** [comment]
Thank you @jkomyno for all your help in tackling this issue. 
I think we can consider this issue fixed.

**Comment by jkomyno** [comment]
Closed PR as it's deprecated in favor of https://github.com/jkomyno/reprod-14539.

**Pull request closed without merging**
