### PR TITLE
Fix #2945 Cannot run on OpenShift

### LINKED ISSUE #2945: Cannot run on OpenShift.
**Describe the bug**
The Docker images cannot be run on OpenShift, or at least not under the defaults.  This might count as a feature, I'm not sure.

**To Reproduce**
1.) `oc cluster up`
2.) `oc new-app --docker-image=prismagraphql/prisma:1.14`
3.) `oc status` will eventually say something like "Errors: pod/prisma-whatever is crash-looping"
4.) `oc logs pod/prisma-whatever` shows "/app/start.sh: line 3: ./app/bin/prisma-local: Permission denied"

**Expected behavior**
It should start up.

**Versions (please complete the following information):**
 - OS: Ubuntu 18 
 - `prisma` CLI: N/A
 - Prisma Server: 1.14

**Additional context**
I think it's just because of the permissions on `app/bin/prisma-local`.  If you run `docker run --entrypoint "whoami" prismagraphql/prisma:1.14` it says the container's running under root user, so maybe it'd be a matter of making it be under a non-root user?

### PR DESCRIPTION
**Pull request by sapkra**
Add execution rights for root group to `/app/bin/prisma-local` to fix the following error:

```bash
/app/start.sh: line 3: ./app/bin/prisma-local: Permission denied
```

The reason is that OpenShift is running the container with random UIDs they are stil in the root group. They are doing it to prevent to run the container with the root user for security reasons.

Fix #2945

### CODE REVIEW

**Comment by Aubron** [comment]
Solid, and fixes the issue at the origin of #2945, which Bandwidth is currently having to work around.

**Comment by dpetrick** [comment]
Rebase onto current changes please @sapkra and I will review / merge. Thanks.

**Comment by sapkra** [comment]
@dpetrick I rebased my branch and resolved the conflicts.

**Comment by dpetrick** [comment]
@sapkra Thank you for the contribution.

**Pull request merged**
