### PR TITLE
fix(client): adjust grammar on engines warning

### PR DESCRIPTION
**Pull request by chenkie**
Hi team 👋

I've been seeing the "too many engines" warning in my console for some time now and thought the grammar could be improved.

### CODE REVIEW

**Review by millsp — APPROVED** [review]

**Comment by Jolg42** [comment]
Thanks!

It will also need an update here in docs https://github.com/prisma/docs/blob/main/content/500-support/100-help-articles/400-nextjs-prisma-client-dev-practices.mdx?plain=1#L12

**Review by Jolg42 — APPROVED** [review]

**Comment by millsp** [comment]
Thanks for pointing that out @Jolg42 :pray:  https://github.com/prisma/docs/pull/2621

**Comment by millsp** [comment]
Thanks for your PR @chenkie :pray:

**Comment by janpio** [comment]
Nitpick: Technically the error message is not necessarily about the engine, but really multiple instances of Prisma Client (each with its own instance of a Query Engine) to avoid.

**Comment by chenkie** [comment]
gotcha! I inferred it from the function its run from: `checkForTooManyEngines`. Feel free to adjust 😄

**Comment by Jolg42** [comment]
Attempt 2, feedback welcome https://github.com/prisma/prisma/pull/10684

**Comment by janpio** [comment]
Thanks for the follow up - now we fixed the code as well to reflect what we actually mean here - both code and warning message are in a much better state.

**Pull request merged**
