### PR TITLE
fix(client): Reexporting in the way that cjs-module-lexer can detect

### PR DESCRIPTION
**Pull request by janpio**
Pulled in version of https://github.com/prisma/prisma/pull/12907 so integration version is released.

### CODE REVIEW

**Comment by janpio** [comment]
This was published as `prisma@3.14.0-integration-tnzk-feature-esm-friendly-reexports.1`

**Comment by janpio** [comment]
And now `prisma@3.14.0-integration-tnzk-feature-esm-friendly-reexports.2`.

**Comment by janpio** [comment]
And now `prisma@3.14.0-integration-tnzk-feature-esm-friendly-reexports.3` (and `@prisma/client`)

**Comment by janpio** [comment]
This PR makes a ecoystem-test that used to fail, work: https://github.com/prisma/ecosystem-tests/pull/2695
Failing: https://github.com/prisma/ecosystem-tests/runs/6196978275?check_suite_focus=true
Passing: https://github.com/prisma/ecosystem-tests/runs/6201558652?check_suite_focus=true

**Comment by tnzk** [comment]
@janpio thank you Jan for taking care of all of this! Btw, what was the motivation behind `backup-index.js` in the end? would like to know just for my curiosity :)

**Comment by janpio** [comment]
I'll let you know when we can figure it out :D

**Comment by janpio** [comment]
merged as https://github.com/prisma/prisma/pull/12907

**Comment by Jolg42** [comment]
Closing since original PR was merged

**Pull request closed without merging**
