### PR TITLE
config(client): ignore dmmf types

### PR DESCRIPTION
**Pull request by danstarns**
This file keeps being changed when running the test suite, we don't actually need it in source control and so this PR removes it. 

image

### CODE REVIEW

**Review by SevInf — APPROVED** [review]

**Comment by danstarns** [comment]
> 

Oh no :/ Where does this happen? I only found one occurrence of this when searching the codebase and that was writing to disk and asserting that we can import that file.

**Comment by millsp** [comment]
No worries, revert is easy. This this where we write it to disk and typecheck it.
https://github.com/prisma/prisma/blob/7c32eccba7f0c2b1891e8e107fa14097ab7cf44b/packages/client/src/__tests__/integration/happy/exhaustive-schema/dmmf-types.test.ts/#L15-L26

**Comment by danstarns** [comment]
> No worries, revert is easy. This this where we write it to disk and typecheck it. https://github.com/prisma/prisma/blob/7c32eccba7f0c2b1891e8e107fa14097ab7cf44b/packages/client/src/__tests__/integration/happy/exhaustive-schema/dmmf-types.test.ts/#L15-L26

Are we sure these are the same thing, that linked test is associated with `generated-dmmf.ts` not `__helpers__/dmmf-types.ts` ?

**Comment by millsp** [comment]
Yep, sorry about that. The one I linked does check the work of checking types. This one https://github.com/prisma/prisma/blob/3770bb3b4ab3a7bffbeefe1d1e5231e50fbb7d3b/packages/client/src/__tests__/dmmfTypes.test.ts/#L32-L43 is for you to see eventual changes to the dmmf when it changes (eg. via a Prismo PR for a new engine).

**Pull request merged**
