### PR TITLE
Fix missing UUID in where clause.

### LINKED ISSUE #2879: Incomplete UUID query support with PostgreSQL
**Describe the bug**
WhereInput doesn't dispaly ID field when using UUID

**To Reproduce**
1. Init Prisma
2. Create relationship with UUID model
```
type User {
  id: UUID! @unique
  name: String!
  posts: [Post!]!
}

type Post {
  id: UUID! @unique
  body: String!
  author: User!
}
```
4. Start container and deploy
5. Try to find posts by author
```
query($id: ID!) {
  posts(where: { author: { id: $id } }) {
    id
    body
    author {
      id
    }
  }
}
```
image

The same query with the default ID works well.

**Expected behavior**
To behavior as default ID

Versions:
 - Prisma Server: 1.15-alpha

**Additional context**
I'm a bit afraid to use UUIDs with Prisma in these first steps. Although they scale well in my application I do not know if I can find other problems in the future that can lead to data loss or inconsistency.
Any suggestions from the team to avoid complications in the future regarding IDs?

Despite this, the team is being amazing in implementing the project and creating tools to help developers, keep up the good work! 🎉🎉

### PR DESCRIPTION
**Pull request by yckao**
Fixes #2879 #3670 #3757

### CODE REVIEW

**Comment by do4gr** [comment]
This looks good as well, thanks again!

I have the same comments as for the other PR, please target it at Master and add the following test case file: 

```
package com.prisma.api.filters.nonEmbedded

import com.prisma.api.ApiSpecBase
import com.prisma.shared.models.ConnectorCapability.UuidIdCapability
import com.prisma.shared.models.Project
import com.prisma.shared.schema_dsl.SchemaDsl
import org.scalatest.{FlatSpec, Matchers}

class UUIDFilterSpec extends FlatSpec with Matchers with ApiSpecBase {
  override def runOnlyForCapabilities = Set(UuidIdCapability)

  val project: Project = SchemaDsl.fromString() { """
                                                   |type User {
                                                   |  id: UUID! @unique
                                                   |  name: String!
                                                   |}""".stripMargin }

  override protected def beforeAll(): Unit = {
    super.beforeAll()
    database.setup(project)
  }

  "Using a UUID field in where clause" should "work" in {
    server.query("""query {users(where: { id: "a3f7bcd1-3ae7-4706-913a-9cfe5ed7e7b6" }) {id}}""", project).toString should be("""{"data":{"users":[]}}""")
  }
}
```

**Comment by yckao** [comment]
Thanks again.
Prisma is a awesome project about create graphql server.
I'm glad to contribute the project.

**Comment by do4gr** [comment]
I ran the tests for both your PRs on a separate branch https://github.com/prisma/prisma/pull/3793 . There is only one small change needed for this PR and then I can merge both of them. 

Can you change the UUIDFilterSpec to this: 

```
package com.prisma.api.filters.nonEmbedded
  
   import com.prisma.api.ApiSpecBase
  import com.prisma.shared.models.ConnectorCapability.UuidIdCapability
  import com.prisma.shared.models.Project
  import com.prisma.shared.schema_dsl.SchemaDsl
  import org.scalatest.{FlatSpec, Matchers}
  
   class UUIDFilterSpec extends FlatSpec with Matchers with ApiSpecBase {
    override def runOnlyForCapabilities = Set(UuidIdCapability)
  
     "Using a UUID field in where clause" should "work" in {
      val project: Project = SchemaDsl.fromString() { """
                                                     |type User {
                                                     |  id: UUID! @unique
                                                     |  name: String!
                                                     |}""".stripMargin }
      database.setup(project)
      server.query("""query {users(where: { id: "a3f7bcd1-3ae7-4706-913a-9cfe5ed7e7b6" }) {id}}""", project).toString should be("""{"data":{"users":[]}}""")
    }
   }
```

**Comment by do4gr** [comment]
I just cut a release with your two PRs. Thanks again for the contribution!

**Pull request merged**
