### PR TITLE
[do not merge]  refactor:remove eval

### PR DESCRIPTION
**Pull request by soilSpoon**
I'm thinking of removing eval using [external](https://esbuild.github.io/api/#external)

### CODE REVIEW

**Comment by Jolg42** [comment]
So eval is used because of how bundlers work.
The tests might pass here but it would probably break when using webpack and others.

**Comment by soilSpoon** [comment]
> So eval is used because of how bundlers work. The tests might pass here but it would probably break when using webpack and others.

If it works using eval, doesn't it work without it?

It is beyond my knowledge to understand this phenomenon. Do you have any related documents?

**Comment by pantharshit00** [comment]
I think we did this to prevent asset relocation which bundlers do which is basically changing values of `__dirname`, `process.cwd()` by bundlers. I also remember there were some issues with vercel/ncc which required these annotations. 

@Jolg42 should have more information here though.

**Comment by soilSpoon** [comment]
> I think we did this to prevent asset relocation which bundlers do which is basically changing values of `__dirname`, `process.cwd()` and other variables by bundlers. I also remember there were some issues with vercel/ncc which required these annotations.
> 
> @Jolg42 should have more information here though.

Thank you for a detailed description! If I do more research and the problems you mentioned are resolved, would it be good to reflect the modifications?

**Pull request closed without merging**
