### PR TITLE
fix(db push): make sure to stop migrate engine when it errors

### PR DESCRIPTION
**Pull request by Jolg42**
Related
https://github.com/prisma/prisma/issues/7795
https://github.com/prisma/prisma/pull/7990

Thanks @millsp for finding the test that uncovered this 👍🏼

### CODE REVIEW

**Review by millsp — APPROVED** [review]
Awesome!

**Review by janpio — CHANGES_REQUESTED** [review]
Nice, good catch!

Test not passing though yet.

**Comment by millsp** [comment]
If you can't reproduce this locally, let me know.

**Comment by Jolg42** [comment]
Ok I'll merge main later and see what this is about

**Comment by janpio** [comment]
That's the danger of the timeouts I think - they cancel the job, and do not fail it by default.

**Comment by Jolg42** [comment]
Yes... but better that it times out after 10 minutes than 6 hours by default 😄

**Pull request merged**
