### PR TITLE
ci: disable "typescript compilation" benchmark under CodSpeed

### PR DESCRIPTION
**Pull request by aqrln**

### CODE REVIEW

**Comment by millsp** [comment]
CodSpeed is now completely disabled, was that intentional?

**Comment by aqrln** [comment]
@millsp it didn't run because of a typo that made the workflow file invalid, should be fixed now

**Review by millsp — APPROVED** [review]

**Comment by millsp** [comment]
image :trollface:

**Comment by aqrln** [comment]
@millsp I think it's red because of a removed benchmark, not because of the regression. Our current configured threshold should be 10% I believe.

**Comment by millsp** [comment]
Nice, thanks for the context.

**Pull request merged**
