### PR TITLE
CLI: Rename Prisma 2 to Prisma Framework

### PR DESCRIPTION
**Pull request by nikolasburk**
I've adjusted the wording in the `prisma2` CLI commands to reference the "Prisma Framework" instead of "Prisma 2".

### CODE REVIEW

**Comment by schickling** [comment]
LGTM

**Review by janpio — APPROVED** [review]

**Comment by janpio** [comment]
(I still think we should have a definitive decision if it should be `Prisma Framework` or `the Prisma Framework`)

**Comment by williamluke4** [comment]
- Prisma Framework = 🚀
- The Prisma Framework = 🎉

**Comment by jedmao** [comment]
It used to be TheFacebook... _used to be._

**Pull request merged**
