### PR TITLE
fix: see if studio tests fail on windows

### PR DESCRIPTION
**Pull request by eemmiillyy**
Test to see if studio tests will fail on windows

### CODE REVIEW

**Comment by Jolg42** [comment]
and they fail, nice!

The error is weird though
```
    +     data: null,
    +     error: Object {
    +       code: P500,
    +       message: The underlying schema has changed. Please reload Studio.,
    +       stack: ,
    +       type: PrismaClientSchemaDriftedError,
          },
```

**Comment by eemmiillyy** [comment]
Yeah the error is weird :/ @Jolg42, I expect `schemaHash` not to change

**Comment by Jolg42** [comment]
Might be because line ending and windows, always a funny one... 🙈

**Comment by janpio** [comment]
Unfortunately also means that `open`, which is causing the failure on Windows, is not really tested here :/

**Comment by eemmiillyy** [comment]
Yeah this isn't testing whether the `open` package **actually** opens a tab, it's just testing that the call doesn't throw an error. @janpio 
They do something similar in the tests inside the package: https://github.com/sindresorhus/open/blob/main/test.js
But maybe this isn't verifying even that open doesn't show an error because I also expect to see this somewhere: `Cannot open the browser to run studio: + e)` in the logs and I don't

**Comment by janpio** [comment]
Probably swallowed by this: https://github.com/prisma/prisma/blob/cc453c562deb3026c6d96b7c6788ef9e04f9d61d/packages/cli/src/Studio.ts#L138-L145

**Comment by eemmiillyy** [comment]
@janpio I actually changed that line in this PR to throw an error instead of silently fail 
https://github.com/prisma/prisma/pull/9033/files#diff-567c0692a5fdbc9e5017337b5e30c97a1f1b1b39e3a855ec68bd09ee28f65010R144

**Comment by janpio** [comment]
Ah now I know what you mean. And am even more confused.

**Pull request closed without merging**
