### PR TITLE
fix(client): allow readonly array and object as JSON input

### LINKED ISSUE #10165: JSONValue not accepting readonly array or objects
### Bug description

Due to code bellow
```ts
export type InputJsonObject = {[Key in string]?: JsonValue}

export interface InputJsonArray extends Array<JsonValue> {}

export type InputJsonValue = string | number | boolean | InputJsonObject | InputJsonArray
```

```
Type 'readonly ImmutableObject<{ lat: number; lng: number; }>[]' is not assignable to type 'InputJsonValue'.
  Type 'readonly ImmutableObject<{ lat: number; lng: number; }>[]' is not assignable to type 'InputJsonArray'.ts(2322)
```

### How to reproduce

1. Create a model with JSON column
2. Try to create a row in it using read-only object/array
3. See error

### Expected behavior

The input of JSON definitely should accept read-only values.

If the JSON input types were read-only, then updating JSON columns of a table would accept read-write and read-only values!

```ts
export type InputJsonObject = {readonly [Key in string]?: JsonValue}

export interface InputJsonArray extends Readonlyarray<JsonValue> {}

export type InputJsonValue = string | number | boolean | InputJsonObject | InputJsonArray
```

### Environment & setup

- OS: Windows 11
- Database: MySQL
- Node.js version: v14.15.4

### Prisma Version

```
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

### PR DESCRIPTION
**Pull request by Akxe**
Allow both readonly and mutable arrays and objects as JSON input values.

Closes https://github.com/prisma/prisma/issues/10165

### CODE REVIEW

**Comment by aqrln** [comment]
Hi @Akxe and thank you for your PR 👍💯

There are some failing tests on CI, seem to be the snapshot tests only. Could you please update the snapshots? If not, that's also fine, I can do that as well.

**Comment by Akxe** [comment]
@aqrln Sadly I am not sure how I did the change in the browser...

**Comment by Akxe** [comment]
Is the `buildkite/test-prisma-typescript/pr` error a false negative?

**Comment by aqrln** [comment]
Yes, MongoDB failed to start:

```
[2021-11-25T10:16:27Z] ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint buildkite51bb967838824f0ba115922e0cb4f79d_mongo_1 (b80373ee0cc3f374efbd0f4862e8340076e4b263219e8045a30572431fd13850): Bind for 0.0.0.0:27017 failed: port is already allocated
```

**Comment by Akxe** [comment]
Is it then good to go?

**Comment by aqrln** [comment]
Added `tsd` tests as well.

**Comment by Akxe** [comment]
Cool did not think of that :)

**Comment by aqrln** [comment]
@Akxe 

> Is it then good to go?

Pending review from others, yes.

Assuming I didn't miss something important and nothing unexpected happens, this should hopefully make it into the 3.6.0 release.

**Comment by Akxe** [comment]
This is quite a bit more work than anticipated :/

**Review by Jolg42 — APPROVED** [review]
Thanks! And 💯 for the tests!

**Pull request merged**
