### PR TITLE
feat: use `only-allow` to enforce installation with `pnpm`

### PR DESCRIPTION
**Pull request by safinsingh**
See title; allows for cleaner, less "janky" script.

### CODE REVIEW

**Comment by safinsingh** [comment]
The usage of the `-y` flag seems to be an issue with `npm@6`. I'm removing it in order to let the tests pass. With `npm@7`, it will prompt for confirmation before installing, but that shouldn't be an issue because people running `npm@7` will be doing so in interactive mode.

**Review by khrj — APPROVED** [review]

**Comment by timsuchanek** [comment]
Thanks for the contribution! Makes the code much nice.

**Comment by Jolg42** [comment]
It looks nice but now it's one more potential security issue though 😅

**Comment by pantharshit00** [comment]
@Jolg42 Looks like `only-allow` is authored by `pnpm` so if we trust pnpm, we can trust that as well.

**Comment by Jolg42** [comment]
I know but temporary attacks are also a thing and executing some code without specifying the version means it's open bar 🤷

`npx only-allow@1.0.0 pnpm` fixes that.

**Comment by Jolg42** [comment]
I pinned it ✅

**Pull request merged**
