### PR TITLE
fix(client): HasReject fix for RejectPerOperation case

### LINKED ISSUE #11403: HasReject not evaluating correctly for per operation handlers
### Bug description

We have Prisma configured to throw a custom exception on `findUnique`, and with `strictNullChecks` turned on, expect the return type of `findUnique` to not be nullable.  However, the current return type is `PrismaPromise<ModelType | null>`. After doing some digging, I think the issue is [here](https://github.com/prisma/prisma/blob/d4dbc69e63afd2c10ac72b195a29cd56097c08c9/packages/client/src/generation/TSClient/PrismaClient.ts#L230).  The case where the `Action` is a boolean is handled, and the case where `Action` extends `RejectPerModel` is handled, just not the `RejectPerOperation` case

### How to reproduce

1. Create a fresh Prisma project from the quickstart [here](https://www.prisma.io/docs/getting-started/quickstart)
2. Update `script.ts` with the below
```
const prisma = new PrismaClient({
  rejectOnNotFound: { findUnique: (err) => {
    throw new Error('test')}}
})

// A `main` function so that you can use async/await
async function main() {
  // ... you will write your Prisma Client queries here
  const {id } = await prisma.post.findUnique({where:{ id: 123}})
}
```
3. turn on the `strictNullChecks` compiler flag
4. The return type of `findUnique` will be nullable

### Expected behavior

The return type is not nullable

### Prisma information

```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 16.13.0

### Prisma Version

```
prisma                  : 3.6.0
@prisma/client          : 3.6.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : dc520b92b1ebb2d28dc3161f9f82e875bd35d727
Studio                  : 0.440.0
Preview Features        : interactiveTransactions
```

### PR DESCRIPTION
**Pull request by jasimon**
Closes #11403

### CODE REVIEW

**Comment by Jolg42** [comment]
Thanks for your PR @jasimon 

My colleague will check this later when he has capacity.
Note: The issue looks great and will have to be processed first for a confirmed reproduction.

In the meantime, in case this is the fix needed we would need you to sign the CLA, see message above ⬆️ 
You can see the email used for your commit here for adding it to your GitHub account like mentioned [in the message](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) https://github.com/prisma/prisma/commit/f848a34b7d06c60302e855eb5a0dd49396e4843a.patch

**Comment by jasimon** [comment]
@Jolg42 not sure what's happening with the two outstanding failing tests, https://github.com/prisma/prisma/runs/5010667383?check_suite_focus=true#step:11:1569 looks like it's a timeout issue (unrelated to the changes) and the error at https://buildkite.com/prisma/test-prisma-typescript/builds/11500#793ae811-d22f-4970-b58e-430211d914a0 seems unrelated as well but let me know if I'm missing something there.

**Comment by Jolg42** [comment]
@jasimon Looks like all tests are passing! Sometimes some flaky tests can fail, like what you mentioned.

**Comment by Jolg42** [comment]
Now my colleagues @millsp and @aqrln need to review this

**Review by aqrln — APPROVED** [review]
Looks good to me, thank you! Sorry for the delay.

**Comment by aqrln** [comment]
I can't push to this PR, either the OP has disabled the option for maintainers to amend pull requests, or something went wrong on GitHub. Here's the final test run on the rebased branch (Buildkite only): https://buildkite.com/prisma/test-prisma-typescript/builds/12021

**Pull request merged**
