### PR TITLE
feat: client esm support

### PR DESCRIPTION
**Pull request by timsuchanek**
Continuing #4178 and #4265
Closes prisma/prisma-client-js#539

### CODE REVIEW

**Comment by timsuchanek** [comment]
Update: I'm dropping this for now, as I looked into it already for a few hours and couldn't get it working.
The main challenge is, to keep all the old code working, while supporting ESM.
We can't choose ESM as the default, because we still support Node 10. Once we don't support that anymore, that would be much easier.
The optimal solution would be, that we can support it without adding the `"exports"` property to the `package.json`, because then `read-pkg` doesn't work anymore, which we rely on.
The other option, how I could get ESM working, but broke the old setup: Using `"type": "module"`.
However, that again broke the old test setup and code to resolve the modules.

The good news: There is a workaround.
Instead of
```ts
import { PrismaClient } from '@prisma/client'
```
you can just do
```ts
import Prisma from '@prisma/client'
const { PrismaClient } = Prisma
```

**Comment by s-go-bazzinga** [comment]
> Update: I'm dropping this for now, as I looked into it already for a few hours and couldn't get it working.
> The main challenge is, to keep all the old code working, while supporting ESM.
> We can't choose ESM as the default, because we still support Node 10. Once we don't support that anymore, that would be much easier.
> The optimal solution would be, that we can support it without adding the `"exports"` property to the `package.json`, because with `exports`, `read-pkg` doesn't work anymore, which we rely on.
> The other option, how I could get ESM working, but broke the old setup: Using `"type": "module"`.
> However, that again broke the old test setup and code to resolve the modules.
> 
> The good news: There is a workaround.
> Instead of
> 
> ```ts
> import { PrismaClient } from '@prisma/client'
> ```
> 
> you can just do
> 
> ```ts
> import Prisma from '@prisma/client'
> const { PrismaClient } = Prisma
> ```
> 
> So if anyone wants to pick this up, try to get this working with a test project, which has `"type": "module"` activated and find out, why for example `sort-es` works.

Hi @timsuchanek, now that [the 2.25.0 release](https://github.com/prisma/prisma/releases/tag/2.25.0) drops support for NodeJS 10, can we add support for ESM exports?

I need this for use within a SvelteKit project that use `type: "module"` and Vite as a bundler.

**Comment by saikatdas0790** [comment]
> Update: I'm dropping this for now, as I looked into it already for a few hours and couldn't get it working.
> The main challenge is, to keep all the old code working, while supporting ESM.
> We can't choose ESM as the default, because we still support Node 10. Once we don't support that anymore, that would be much easier.
> The optimal solution would be, that we can support it without adding the `"exports"` property to the `package.json`, because with `exports`, `read-pkg` doesn't work anymore, which we rely on.
> The other option, how I could get ESM working, but broke the old setup: Using `"type": "module"`.
> However, that again broke the old test setup and code to resolve the modules.
> 
> The good news: There is a workaround.
> Instead of
> 
> ```ts
> import { PrismaClient } from '@prisma/client'
> ```
> 
> you can just do
> 
> ```ts
> import Prisma from '@prisma/client'
> const { PrismaClient } = Prisma
> ```
> 
> So if anyone wants to pick this up, try to get this working with a test project, which has `"type": "module"` activated and find out, why for example `sort-es` works.

Hi @timsuchanek, now that [the 2.25.0 release](https://github.com/prisma/prisma/releases/tag/2.25.0) drops support for NodeJS 10, can we add support for ESM exports?

I need this for use within a SvelteKit project that use `type: "module"` and Vite as a bundler.

**Comment by benbender** [comment]
@timsuchanek I would like to second the question above. Not only svelte/sveltekit-users would be happy about this, but the whole vite-ecosystem and modern-js at large. The demand is and will be growing :) So +1 for pushing this up in priority.

**Comment by janpio** [comment]
Are your use cases fully covered by https://github.com/prisma/prisma/issues/5030? That is the issue that would actually get prioritized by us, so please leave a comment with more information there. Thanks.

**Comment by benbender** [comment]
@janpio If the issue resolves to support of [ES Modules](https://nodejs.org/api/esm.html), it should, yes! Thanks for prioritizing this!

**Comment by GauBen** [comment]
@saikatdas0790 @benbender If this is still relevant, [I found a workaround.](https://github.com/prisma/prisma/discussions/9027)

**Comment by learnitmyway** [comment]
I added this workaround:

```js
import pkg, { PrismaClient } from '@prisma/client'

let prisma

if (process.env.NODE_ENV === 'production') {
  const { PrismaClient: PrismaClientProd } = pkg
  prisma = new PrismaClientProd()
} else {
  prisma = new PrismaClient()
}

export default prisma
```

**Comment by dslatkin** [comment]
> I added this workaround:
> 
> ```js
> import pkg, { PrismaClient } from '@prisma/client'
> 
> let prisma
> 
> if (process.env.NODE_ENV === 'production') {
>   const { PrismaClient: PrismaClientProd } = pkg
>   prisma = new PrismaClientProd()
> } else {
>   prisma = new PrismaClient()
> }
> 
> export default prisma
> ```

Thank you for this comment! That worked for me. For anybody else trying to also get this to work with TypeScript in Node v16, [my comment here](https://github.com/prisma/prisma/discussions/9027#discussioncomment-1585810) was ultimately how I did it.

**Comment by leppaott** [comment]
> I hate to be this guy but are there any updates on this? The workarounds mentioned don't seem to work for me and generally having this feature is a nice thing

```
SyntaxError: Named export 'Prisma' not found. The requested module 'prisma/prisma-client/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'prisma/prisma-client/index.js';
const { Prisma } = pkg;
```

But this would be nice indeed.

**Comment by McGaelen** [comment]
Would be awesome to see this merged/prioritized - SvelteKit recently moved to using Rollup when building for nodejs, and now Prisma fails at runtime for me:
```
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/<sveltekit-project-dir>/build/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at ../../node_modules/.pnpm/@prisma+engines@3.16.0-49.da41d2bb3406da22087b849f0e911199ba4fbf11/node_modules/@prisma/engines/dist/index.js (file:///<sveltekit-project-dir>/build/server/chunks/index-7446c8e5.js:28356:31)
    ...(other lines omitted)
```
I can't change the name to .cjs obviously because that's part of the build output, and SvelteKit requires your project to be "type": "module".
None of the listed workarounds work for me, so my only option will be to likely use a different ORM entirely 😥

**Comment by janpio** [comment]
Please open an issue about this explicitly @McGaelen so we can track this as a bug and problem. Thanks.

**Comment by leppaott** [comment]
Can someone confirm has something happened to this or am I dreaming?

I mean we used above workarounds with ESM modules but now:

```
import { Prisma, PrismaClient } from '@prisma/client';
let prismaInstance: PrismaClient;
prismaInstance = new PrismaClient(prismaConfig);
```

Not only finds the type PrismaClient but also the constructor! We still have `"type": "module"` but we have updated TS into 4.8, so I wonder has ESM work on TS 4.7 affected this somehow?

It works on runtime where before it didn't....

**Comment by millsp** [comment]
Closing in favor of https://github.com/prisma/prisma/pull/19184

**Pull request closed without merging**
