### PR TITLE
fix(client): discard empty paths

### LINKED ISSUE #9435: no such file or directory, open '/path/schema.prisma' since 3.1.1
### Bug description

When I call ` new PrismaClient()`, I get the error 
```bash
(node:12802) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/mnt/d/workspace/path/packages/api/src/schema.prisma'
```
That just happen on 3.1.1

### How to reproduce

1. Upgrade prisma to 3.1.1
2. Execute `prisma db push` command
3. Call ` new PrismaClient()`

### Expected behavior

_No response_

### Environment & setup

- OS: Windows(wsl)
- Database: SQLite
- Node.js version: v14.17.4

### Prisma Version

```
prisma                  : 3.1.1
@prisma/client          : 3.1.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine c22652b7e418506fab23052d569b85d3aec4883f (at ../../.yarn/unplugged/@prisma-engines-npm-3.1.0-24.c22652b7e418506fab23052d569b85d3aec4883f-4e2ba773cc/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli c22652b7e418506fab23052d569b85d3aec4883f (at ../../.yarn/unplugged/@prisma-engines-npm-3.1.0-24.c22652b7e418506fab23052d569b85d3aec4883f-4e2ba773cc/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core c22652b7e418506fab23052d569b85d3aec4883f (at ../../.yarn/unplugged/@prisma-engines-npm-3.1.0-24.c22652b7e418506fab23052d569b85d3aec4883f-4e2ba773cc/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt c22652b7e418506fab23052d569b85d3aec4883f (at ../../.yarn/unplugged/@prisma-engines-npm-3.1.0-24.c22652b7e418506fab23052d569b85d3aec4883f-4e2ba773cc/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : c22652b7e418506fab23052d569b85d3aec4883f
Studio                  : 0.423.0
```

### PR DESCRIPTION
**Pull request by millsp**
Replaces
~~https://github.com/prisma/prisma/pull/11829~~
https://github.com/prisma/prisma/pull/10804

Goes with https://github.com/prisma/e2e-tests/pull/2488

Closes https://github.com/prisma/prisma/issues/9435

### CODE REVIEW

**Review by Jolg42 — APPROVED** [review]
Nice and clean ✨

**Comment by millsp** [comment]
Hey @Faithfinder, thanks for pointing that out. This PR does exactly what https://github.com/prisma/prisma/pull/11829 does, which means that it is not a fix. I will point your comment there to find a solution.

**Comment by JonParton** [comment]
@millsp  Any idea when this is going to be published out as a `3.11`? 

This fixes https://github.com/prisma/prisma/issues/9435 which is an issue I was having also (as well as all the others mentioning it!)

**Comment by millsp** [comment]
Hey @JonParton, this PR will be published in two weeks from now. If you really need it now, you can temporarily use the integration version that I shared in a comment in the related issue.

**Pull request merged**
