### PR TITLE
feat: add dbVersion to introspection panic report & migrate

### PR DESCRIPTION
**Pull request by Jolg42**
Done in engines with https://github.com/prisma/prisma-engines/pull/1115/files

### CODE REVIEW

**Review by pantharshit00 — CHANGES_REQUESTED** [review]
Please ping me before merging this. I will need to add that field to the backend and deploy it :) 

Blocking this PR for now.

**Comment by Jolg42** [comment]
Sure I think it will be best to wait for https://github.com/prisma/prisma/issues/3788 first anyway :)

**Comment by Jolg42** [comment]
After it's done it will unblock https://github.com/prisma/prisma/issues/3486

**Comment by Jolg42** [comment]
@pantharshit00 this will be merged soon after a PR review, @pantharshit00 I think it's not a problem to merge this before you actually implement it (data will be missing in the reporting and will appear after you implement it, only for the issues reported after you implemented)

**Comment by pantharshit00** [comment]
@Jolg42 Backend change for this was implemented. This is ready to go from my end

**Review by pantharshit00 — APPROVED** [review]

**Review by timsuchanek — APPROVED** [review]
Good work!

**Pull request merged**
