### PR TITLE
fix(preinstall): yarn install messages when using yarn

### PR DESCRIPTION
**Pull request by mongolyy**

### CODE REVIEW

**Comment by janpio** [comment]
Thank you @mongolyy - what an oversight from us.

**Comment by Jolg42** [comment]
Thank you @mongolyy !

**Comment by Jolg42** [comment]
Note: This still needs to be published manually to `@prisma/cli` package

**Comment by Jolg42** [comment]
I published this in `@prisma/cli@2.20.1` example output 
```
┌─────────────────────────────────────────────────────────────────────────────┐
│                                                                             │
│     The package @prisma/cli has been renamed to prisma.                     │
│                                                                             │
│     Please uninstall @prisma/cli first.                                     │
│     Then install prisma to continue using Prisma CLI:                       │
│                                                                             │
│         # Uninstall old CLI                                                 │
│         yarn remove @prisma/cli                                             │
│                                                                             │
│         # Install new CLI                                                   │
│         yarn add prisma --dev                                               │
│                                                                             │
│         # Invoke via npx                                                    │
│         yarn prisma --help                                                  │
│                                                                             │
│     Learn more here: https://github.com/prisma/prisma/releases/tag/2.16.0   │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this .....

```

**Pull request merged**
