### PR TITLE
fix(db pull): add code 104 warning

### PR DESCRIPTION
**Pull request by Jolg42**
Related https://github.com/prisma/prisma-engines/pull/2697

### CODE REVIEW

**Review by millsp — APPROVED** [review]

**Comment by millsp** [comment]
Is it possible to add a test for this?

**Comment by Jolg42** [comment]
We have little tests about this as of today, as we rely on introspection-ci project for these.

**Comment by Jolg42** [comment]
We could focus on adding tests here one day

**Comment by janpio** [comment]
Starting with error codes or warning messages like this here would be an easy way to do that. Can you create an issue @Jolg42?

**Comment by Jolg42** [comment]
@janpio see https://github.com/prisma/prisma/issues/12472

**Pull request merged**
