### PR TITLE
chore: cleanup files[] pkg.json

### PR DESCRIPTION
**Pull request by Jolg42**
The package.json "files: []" is only additive
To remove __tests__ from dist they need to be excluded from tsconfig.json

### CODE REVIEW

**Comment by Jolg42** [comment]
Note exluding src/__tests__ in tsconfig throws errors like 
```
> @prisma/sdk@0.0.0 lint src/packages/sdk
> eslint --cache --fix --ext .ts .


/Users/j42/Dev/prisma-ter/src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/__tests__/getGenerators/getGenerators.test.ts.
The file must be included in at least one of the projects provided
```

Adding a `tsconfig.esling.json` for ESLint like this fixes that
```
{
  "extends": "./tsconfig",
  "include": ["src"],
  "exclude": []
}
```

Mentions
https://github.com/typescript-eslint/typescript-eslint/issues/1174#issuecomment-549990519
https://github.com/typescript-eslint/typescript-eslint/issues/1350

**Review by williamluke4 — APPROVED** [review]

**Comment by Jolg42** [comment]
Merging and checking results in Buildkite 👀

**Comment by Jolg42** [comment]
Update it worked, I see some tests shipped because in utils in one package but it's ok for now

**Comment by williamluke4** [comment]
Thanks @Jolg42

**Pull request merged**
