### PR TITLE
fix(engine-core): Incorrect error message for platform

### PR DESCRIPTION
**Pull request by Josh-a-e**
Fix error message

### CODE REVIEW

**Review by aqrln — APPROVED** [review]
This looks good to me. Would you mind adding a small test for this as well?

**Comment by Josh-a-e** [comment]
I’m sorry, I don’t have time.
________________________________

**Comment by Fdril** [comment]
Okay

We're gonna do some works on this.

**Comment by aqrln** [comment]
@Josh-a-e no worries, either me or someone else will add a test before merging then.

@Fdril could you please elaborate what you mean? Do you want to contribute a test to this PR?

**Review by Jolg42 — APPROVED** [review]

**Comment by janpio** [comment]
Please open an issue to create a test then @aqrln @Jolg42 - I would not be able to say if this has no side effects :/

**Comment by Jolg42** [comment]
Added in our tech debt Slack channel and will be processed there ✅

**Pull request merged**
