### PR TITLE
fix(engine-core): null check childprocess

### LINKED ISSUE #3522: Using $disconnect causes error: TypeError: Cannot read property 'signalCode' of undefined
## Bug description
When using `prisma.$disconnect` the following error occurs:

```
TypeError: Cannot read property 'signalCode' of undefined
    at NodeEngine.handleRequestError (/home/mike/test/nextjs-prisma/node_modules/@prisma/client/runtime/index.js:1:111338)
    at /home/mike/test/nextjs-prisma/node_modules/@prisma/client/runtime/index.js:1:126916
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PrismaClientFetcher.request (/home/mike/test/nextjs-prisma/node_modules/@prisma/client/runtime/index.js:1:227796)
    at async Promise.all (index 4)
    at async module.exports../pages/api/hello.js.__webpack_exports__.default (/home/mike/test/nextjs-prisma/.next/server/pages/api/hello.js:138:18)
    at async apiResolver (/home/mike/test/nextjs-prisma/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async DevServer.handleApiRequest (/home/mike/test/nextjs-prisma/node_modules/next/dist/next-server/server/next-server.js:47:397)
    at async Object.fn (/home/mike/test/nextjs-prisma/node_modules/next/dist/next-server/server/next-server.js:39:218)
```

This generally happens when multiple queries are run at once. I created a demo below that runs 10 queries at once.

## How to reproduce

I created an example repo here https://github.com/mikecao/nextjs-prisma
It's a barebones Next.js application with Prisma.io.

1. Run the project
```
npm install
npm run generate
npm run dev
```
2. On the home page, click the `Run test` button. This will make a call to the API at `/api/hello` defined by `/pages/api/hello.js`.
3. Running the test will cause the error.
4. If you comment out the disconnect method, there will be no error.

## Expected behavior

No error should be thrown when using disconnect.

## Prisma information

I used an example prisma schema just so I could generate the client. None of the models are actually used. The test query is simply `SELECT NOW()` run 10 times.

## Environment & setup

- OS: Ubuntu, Windows 
- Database: PostgreSQL 
- Node.js version: 14.8 
- Prisma version: 2.6.1

```

```

### PR DESCRIPTION
**Pull request by williamluke4**
Closes #3522

### CODE REVIEW

**Comment by janpio** [comment]
Some explanation what was happening, why and waht the solution is?

**Comment by williamluke4** [comment]
@janpio I honestly don't really know! I checked to see if the child process was null and then everything seemed to work fine.

**Review by Jolg42 — APPROVED** [review]
👍

**Review by timsuchanek — APPROVED** [review]

**Comment by timsuchanek** [comment]
This can happen, if the child process has already been killed. Thanks for the work @williamluke4 !

**Pull request merged**
