### PR TITLE
refactor(client): added enum for error codes

### PR DESCRIPTION
**Pull request by florestankorp**
I was watching a NestJS tutorial on YouTube and it used Prisma, but when I saw the error messages as strings I thought it might be a good idea to have an enum those, so I just wanted to check if that's something that could be interesting for the project. If so, I will complete the list tomorrow...

Here is the whole list of error codes by the way:
https://www.prisma.io/docs/reference/api-reference/error-reference

### CODE REVIEW

**Comment by Jolg42** [comment]
Note: we have some code like this in multiple places

In private repos
`KNOWN_QUERY_ENGINE_ERROR_CODES`
https://github.com/prisma/data-proxy/blob/165c23b04097f2955d3ade16e7a0529070b90b1c/qe-tools/qe-log-parser/src/lib.rs#L7-L22

`Codes`
https://github.com/prisma/pdp-engines/blob/85b52f723a0667b37b27d25ba637e6e807ac6c3b/lib/prisma/Errors.ts#L3-L11

and in a public one we have something that looks like what you need (⚠️ it's not a public API) 
https://github.com/prisma/reflector/blob/7a2e5ded034d7101b630eebb1f9fe039a3b1e436/src/Errors/index.ts

How do you like the approach in the last one?

**Comment by aqrln** [comment]
Relevant issue: https://github.com/prisma/prisma/issues/11344

**Comment by aqrln** [comment]
Note that even though the alternative we prefer is full type-safe structured errors, an enum with error codes is a nice first step in that direction, which we could start with if there is demand.

As for the approach, I'm generally -1 on hardcoding the list of errors in the client and maintaining it manually. It must be requested from the engine during generation (and https://github.com/prisma/prisma-engines/pull/2451 is a good starting point to make that possible).

**Comment by garrensmith** [comment]
@florestankorp I'm going to close this. we would prefer to implement this in our DMMF first so that it is easier to keep up to date. You can follow along in this ticket https://github.com/prisma/prisma/issues/5040

**Comment by florestankorp** [comment]
> @florestankorp I'm going to close this. we would prefer to implement this in our DMMF first so that it is easier to keep up to date. You can follow along in this ticket #5040

Cheers. Thanks for your message 👍🏽

**Pull request closed without merging**
