### PR TITLE
Small grammar fix

### PR DESCRIPTION
**Pull request by robin-macpherson**
A very minor grammar fix for the documentation.

### CODE REVIEW

**Comment by robin-macpherson** [comment]
Hi @nikolasburk , apologies for tagging you randomly but it appears I missed something when creating this PR and one other #4955 so nobody was added/notified as a reviewer. Would you mind helping me get these approved?

**Comment by robin-macpherson** [comment]
@do4gr I apologize for the random tags, just trying to understand how I can make someone aware that this PR exists since I'm unable to add reviewers and none were added automatically after I signed the CLA. Same problem for #4955 . I must have missed a step somewhere creating my PRs.

Thank you all 🙏🏼

**Comment by nikolasburk** [comment]
Thanks a lot for catching this @robin-macpherson and apologies for the delay 🙌

**Comment by robin-macpherson** [comment]
> Thanks a lot for catching this @robin-macpherson and apologies for the delay 🙌

Thank you @nikolasburk ! Would you mind also merging #4955 ? Also, what's the correct way for me to do this in the future so that I can add you as a reviewer and not have to tag you in a comment?

**Pull request merged**
