### PR TITLE
test(client): higher timeout on exhaustive tests

### PR DESCRIPTION
**Pull request by danstarns**
Increases timeout on long-running exhaustive tests.

~~My observation is that these two tests **bearly** ever pass on both of the `no-docker` test suites, here I skip them based on an environment variable that is passed in when executing those tests. I've done this because I believe these tests to be slowing down the feedback loop and wasting resources.~~

Example error

```
Summary of all failing tests
FAIL src/__tests__/integration/happy/exhaustive-schema-mongo/dmmf-types.test.ts (41.611 s)
  ● dmmf-types
    thrown: "Exceeded timeout of 40000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
       8 |  * Makes sure, that the actual dmmf value and types are in match
       9 |  */
    > 10 | test('dmmf-types', async () => {
         | ^
      11 |   const datamodel = fs.readFileSync(path.join(__dirname, 'schema.prisma'), 'utf-8')
      12 |   const dmmf = await getDMMF({
      13 |     datamodel,
      at Object.<anonymous> (src/__tests__/integration/happy/exhaustive-schema-mongo/dmmf-types.test.ts:10:1)
FAIL src/__tests__/integration/happy/exhaustive-schema/dmmf-types.test.ts (41.594 s)
  ● dmmf-types
    thrown: "Exceeded timeout of 40000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
       8 |  * Makes sure, that the actual dmmf value and types are in match
       9 |  */
    > 10 | test('dmmf-types', async () => {
         | ^
      11 |   const datamodel = fs.readFileSync(path.join(__dirname, 'schema.prisma'), 'utf-8')
      12 |   const dmmf = await getDMMF({
      13 |     datamodel,
      at Object.<anonymous> (src/__tests__/integration/happy/exhaustive-schema/dmmf-types.test.ts:10:1)
          at runMicrotasks (<anonymous>)
Test Suites: 2 failed, 43 skipped, 147 passed, 149 of 192 total
Tests:       2 failed, 258 skipped, 523 passed, 783 total
Snapshots:   434 passed, 434 total
Time:        659.213 s
Ran all test suites.
```

Here is a random select set of workflows where this error occurs: 
1. https://github.com/prisma/prisma/runs/6780773681?check_suite_focus=true
2. https://github.com/prisma/prisma/runs/6763730976?check_suite_focus=true
3. https://github.com/prisma/prisma/runs/6780764561?check_suite_focus=true
4. https://github.com/prisma/prisma/runs/6758802530?check_suite_focus=true

### CODE REVIEW

**Comment by danstarns** [comment]
Never mind, this won't work because of obsolete snapshots. Opened an issue here: 

https://github.com/facebook/jest/issues/12921

**Comment by janpio** [comment]
Are the failing because something loops, or just because something takes a long time?

**Comment by danstarns** [comment]
> exhaustive

Something takes a long time, the exhaustive tests are testing a very large schema, and timing out, in this env, when generating and JSON stringifying the DMMF.

**Comment by danstarns** [comment]
> Are the failing because something loops, or just because something takes a long time?

Something takes a long time, the exhaustive tests are testing a very large schema, and timing out, in this env, when generating and JSON stringifying the DMMF.

**Comment by Jolg42** [comment]
@danstarns Why not "just" increasing the timeout?

Because we want to run these tests on macos and windows since they are "exhaustive" maybe?

It looks like they are slow with a good machine (16s) but on a bad machine (shared macos on GitHub Actions) it apparently can go over our 40s timeout.

So If we put a 80s timeout here we should be good? (or less)

**Comment by danstarns** [comment]
> @danstarns Why not "just" increasing the timeout?
> 
> Because we want to run these tests on macos and windows since they are "exhaustive" maybe?
> 
> It looks like they are slow with a good machine (16s) but on a bad machine (shared macos on GitHub Actions) it apparently can go over our 40s timeout.
> 
> So If we put a 80s timeout here we should be good? (or less)

This is a much better idea thanks! I was just button bashing because of being frustrated with how many times they failed.

**Review by Jolg42 — APPROVED** [review]

**Review by Jolg42 — CHANGES_REQUESTED** [review]
Could you do that for the no-docker only? with something like this at the top of the file it should work (copy pasted from another test, maybe we can have a helper one day)

```js
const isMacOrWindowsCI = Boolean(process.env.CI) && ['darwin', 'win32'].includes(process.platform)
if (isMacOrWindowsCI) {
  jest.setTimeout(80_000)
}
```

**Comment by danstarns** [comment]
> ```js
> const isMacOrWindowsCI = Boolean(process.env.CI) && ['darwin', 'win32'].includes(process.platform)
> if (isMacOrWindowsCI) {
>   jest.setTimeout(80_000)
> }
> ```

Sure, I'll add this to the top of the file. I went to write the helper:

```ts
export function testCITimeout({
  platforms,
  timeout,
  defaultTimeout,
}: {
  platforms: NodeJS.Platform[]
  timeout: number
  defaultTimeout?: number
}) {
  if (!process.env.CI) {
    return
  }

  const isIncluded = platforms.includes(process.platform)

  if (isIncluded) {
    jest.setTimeout(timeout)
  } else if (defaultTimeout) {
    jest.setTimeout(defaultTimeout)
  }
}
```

Then realized that it needs to be used in all packages! So will just copy and paste it and come back to the helper another time.

**Review by Jolg42 — APPROVED** [review]

**Comment by danstarns** [comment]
related: https://github.com/prisma/prisma/pull/13572

**Pull request merged**
