### PR TITLE
test(client): multiSchema, test same table name

### LINKED ISSUE #15009: [Multi Schema] Same model map different schema
### Bug description

I am using multiSchema, and I have the following schema: 

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema"]
}

datasource db {
  provider = "postgresql"
  url      = ...
  schemas  = ["base", "transactional"]
}

model User {
  email String
  posts Post[]

  @@map("some_table")
  @@schema("base")
}

model Post {
  title    String
  authorId String
  author   User?  @relation(fields: [authorId], references: [id])

  @@map("some_table")
  @@schema("transactional")
}

```

The User model belongs to the `base` schema and it is mapped to the `some_table` tabel name. 

The Post model belongs to the `transactional` schema and it is mapped to the `some_table` tabel name. 

I get the error: 

```
Error: Get DMMF: Schema parsing - Error while interacting with query-engine-node-api library
Error code: P1012
error: Error validating: The argument `references` must refer only to existing fields in the related model `User`. The following fields do not exist in the related model: id
  -->  schema.prisma:24
   | 
23 |   authorId String
24 |   author   User?  @relation(fields: [authorId], references: [id])
   | 
error: The model with database name "some_table" could not be defined because another model with this name exists: "User"
  -->  schema.prisma:21
   | 
20 | 
21 | model Post {
22 |   title    String
23 |   authorId String
24 |   author   User?  @relation(fields: [authorId], references: [id])
25 | 
26 |   @@map("some_table")
27 |   @@schema("transactional")
28 | }
   | 
```

### How to reproduce

1. Take the given schema
2. Run `npx prisma migrate dev`

### Expected behavior

Both models map to the same tabel name `some_table` however, they are in different schemas and so this should work. 

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 18.2.0

### Prisma Version

```
dev
```

### PR DESCRIPTION
**Pull request by Jolg42**
Closes https://github.com/prisma/prisma/issues/15009

We previously tested different table names because of a bug in validation, this PR changes that to test the same table name but in 2 different db `schemas`.

### CODE REVIEW

**Review by danstarns — APPROVED** [review]
Looks good to me, I assume we are waiting on an engine's version for this to pass. Happy to merge once its green.

**Comment by Jolg42** [comment]
Waiting for https://github.com/prisma/prisma/pull/15649

**Comment by Jolg42** [comment]
Currently fails with 
https://github.com/prisma/prisma/actions/runs/3189841431/jobs/5204140972#step:10:2842
```
FAIL tests/functional/multi-schema/tests.ts (14.334 s)
  ● multi-schema (provider=postgresql, mapTable=true) › create

    Schema validation error - Error (query-engine-node-api library)
    Error code: P1012
    error: Error parsing attribute "@id": The given constraint name `some_table_pkey` has to be unique in the following namespace: global for primary key, indexes and unique constraints. Please provide a different name using the `map` argument.
      -->  schema.prisma:14
       | 
    13 |     model User {
    14 |       id String @id @default(cuid())
       | 
    error: Error parsing attribute "@id": The given constraint name `some_table_pkey` has to be unique in the following namespace: global for primary key, indexes and unique constraints. Please provide a different name using the `map` argument.
      -->  schema.prisma:23
       | 
    22 |     model Post {
    23 |       id String @id @default(cuid())
       | 

    Validation Error Count: 2
    [Context: getDmmf]
```

**Comment by Jolg42** [comment]
New engines from https://github.com/prisma/prisma-engines/pull/3269 are now showing a different error.

https://github.com/prisma/prisma/actions/runs/3228011532/jobs/5283599499#step:10:4693

```
       db error: ERROR: relation "some_table" already exists
      0: sql_migration_connector::apply_migration::migration_step
                 with step=CreateTable { table_id: TableId(1) }
                   at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:21
      1: sql_migration_connector::apply_migration::apply_migration
                   at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:10
      2: migration_core::state::SchemaPush
                   at migration-engine/core/src/state.rs:380
      Error: db error: ERROR: relation "some_table" already exists
      0: sql_migration_connector::apply_migration::migration_step
                 with step=CreateTable { table_id: TableId(1) }
                   at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:21
      1: sql_migration_connector::apply_migration::apply_migration
                   at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:10
      2: migration_core::state::SchemaPush
                   at migration-engine/core/src/state.rs:380
```
@tomhoule it seems something is missing for `SchemaPush`

**Comment by Jolg42** [comment]
The error is expected because multi schema migrations are not yet implemented

**Comment by Jolg42** [comment]
Since Migrate support is needed to do this test in the functional test suite, I did it in the old integration tests https://github.com/prisma/prisma/pull/15798

**Pull request merged**
