### PR TITLE
fix(client): replace dynamic import for `wasm-worker-loader` with static export

### LINKED ISSUE #23600: Next.js app build fails when using Prisma with DB driver in Server Action
### Bug description

When building a Next.js application using Prisma on the edge runtime with the Database driver, the build fails with the following error. This problem seems to occur when using Prisma client on the server action imported by the client component. Also, this problem did not occur with Prisma v5.10.2 (in Early Access), and occurred with v5.11.0.

```
Failed to compile.

app/page.js from Terser
  x await isn't allowed in non-async function
       ,-[26410:1]
 26410 | /* harmony export */ __webpack_require__.d(__webpack_exports__, {
 26411 | /* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
 26412 | /* harmony export */ });
 26413 | /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ((await Promise.resolve(/* import() */).then(__webpack_require__.t.bind(__webpack_require__, 9737, 23))).default);
       :                                                                         ^^^^^^^
 26414 | 
 26415 | /***/ }),
       `----

Caused by:
    0: failed to parse input file
    1: Syntax Error
Error: 
  x await isn't allowed in non-async function
       ,-[26410:1]
 26410 | /* harmony export */ __webpack_require__.d(__webpack_exports__, {
 26411 | /* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
 26412 | /* harmony export */ });
 26413 | /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ((await Promise.resolve(/* import() */).then(__webpack_require__.t.bind(__webpack_require__, 9737, 23))).default);
       :                                                                         ^^^^^^^
 26414 | 
 26415 | /***/ }),
       `----

Caused by:
    0: failed to parse input file
    1: Syntax Error


> Build failed because of webpack errors
```

### How to reproduce

1. `git clone https://github.com/nzws/prisma-with-nextjs-edge-import-problem-repro`
2. `cd prisma-with-nextjs-edge-import-problem-repro`
3. `yarn install`
4. `yarn build`
5. See error

### Expected behavior

The build passes normally and the application can run.

### Prisma information

I created a repository that can reproduce this issue: https://github.com/nzws/prisma-with-nextjs-edge-import-problem-repro (https://github.com/nzws/prisma-with-nextjs-edge-import-problem-repro/commit/cc513a74a2fc5235409db82e46c51ddf84be4b07)

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

```ts
// ./app/lib/prisma.ts

import { Pool } from "@neondatabase/serverless";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "@prisma/client";

export function createPrismaClient() {
  const neon = new Pool({ connectionString: process.env.DATABASE_URL });
  const adapter = new PrismaNeon(neon);
  const prisma = new PrismaClient({ adapter: adapter });

  return prisma;
}
```

```ts
// ./app/actions.ts

"use server";

import { createPrismaClient } from "./lib/prisma";

export async function onCreate() {
  const prisma = createPrismaClient();

  await prisma.user.create({
    data: {
      email: "john@example.com",
      name: "John Doe",
    },
  });
}
```

```ts
// ./app/client-component.tsx: imported by page.tsx

"use client";

import { onCreate } from "./actions";

export function ClientComponent() {
  const handleCreate = () => {
    void (async () => {
      await onCreate();
    })();
  };

  return (
    <div>
      <h1>Hello, World!</h1>

      <button onClick={handleCreate}>Create User</button>
    </div>
  );
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.10.0

### Prisma Version

```
prisma                  : 5.11.0
@prisma/client          : 5.11.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102
Default Engines Hash    : efd2449663b3d73d637ea1fd226bafbcf45b3102
Studio                  : 0.499.0
Preview Features        : driverAdapters
```

### PR DESCRIPTION
**Pull request by smorimoto**
Fixes #23600

As I understand, since dynamic import is not necessary here, we can easily fix the linked issue.
Is there anything I am missing?
I'm actually using this patch in my runtime environment and I don't see any performance issues either.

### CODE REVIEW

**Comment by jkomyno** [comment]
Thank you @smorimoto for this PR.
I think the next course of action for us is to merge this and observe the impact on our ecosystem-tests.

To summarise the context around this PR for other internal reviewers:
- Next.js uses a non-standard `top-level await` plugin, which can conflict with how we use import the Wasm Query Engine in Prisma: https://github.com/vercel/next.js/issues/31054
- Some users reported similar errors on Next.js + other libraries different than Prisma: https://github.com/vercel/next.js/issues/64792#issuecomment-2068464078
- Some of the Next.js + Prisma users reported that the patch provided by this PR works: https://github.com/prisma/prisma/issues/23600#issuecomment-2080682117
- It looks like recent versions of Next.js 14 recently surfaced this problem to `runtime = "edge"` users: https://github.com/vercel/next.js/issues/64792#issuecomment-2080533446

**Review by dakdevs — APPROVED** [review]
Nice! Glad this is getting fixed. Thank you 🙏🏼 🙏🏼 🙏🏼 🙏🏼

**Comment by smorimoto** [comment]
@jkomyno We migrated some of our projects to the Node.js runtime for performance, but we're still using this patch for some projects that use the Edge runtime, and we don't see any issues, and in theory we don't expect any issues. What are your concerns about merging this?

**Comment by jkomyno** [comment]
Hi @smorimoto, here's some updates on our side:
- This patch currently causes `esbuild` compilation issues when building CommonJS packages, as evidenced by the error in [these ecosystem tests](https://github.com/prisma/prisma/actions/runs/8586883085/job/23555310627?pr=23754#step:5:4250):
  > Top-level await is currently not supported with the "cjs" output format
- My first alternative version of this PR, https://github.com/prisma/prisma/pull/24029, fixes that problem but unfortunately introduced a new problem when using Next.js with Edge middlewares, or Vercel Edge Functions:
  > TypeError: WebAssembly.Instance(): Argument 0 must be a WebAssembly.Module
- Finally, we fixed all of these problems in https://github.com/prisma/prisma/pull/24312, which we merged yesterday.

As posted in https://github.com/prisma/prisma/issues/23600#issuecomment-2135604873, may you please another new unofficial version of Prisma, and report back if it keeps working for your scenario? `5.15.0-integration-client-dynamic-wasm-imports.1`

You can quickly install it via:

```
pnpm add -D prisma@5.15.0-integration-client-dynamic-wasm-imports.1;
pnpm update "@prisma/*" 5.15.0-integration-client-dynamic-wasm-imports.1
```

(please double check that prisma generate has run before retrying).
We expect this to be released with Prisma 5.15.0 next week. Thanks!

**Comment by jkomyno** [comment]
> Hi @smorimoto, here's some updates on our side:
> 
> * This patch currently causes `esbuild` compilation issues when building CommonJS packages, as evidenced by the error in [these ecosystem tests](https://github.com/prisma/prisma/actions/runs/8586883085/job/23555310627?pr=23754#step:5:4250):
>   > Top-level await is currently not supported with the "cjs" output format
> * My first alternative version of this PR, [feat(client): try CJS-friendly alternative to https://github.com/prisma/prisma/pull/23754 #24029](https://github.com/prisma/prisma/pull/24029), fixes that problem but unfortunately introduced a new problem when using Next.js with Edge middlewares, or Vercel Edge Functions:
>   > TypeError: WebAssembly.Instance(): Argument 0 must be a WebAssembly.Module
> * Finally, we fixed all of these problems in [fix(client): fix dynamic wasm imports for Next.js Middlewares / Vercel Edge in `@prisma/client` #24312](https://github.com/prisma/prisma/pull/24312), which we merged yesterday.
> 
> As posted in [#23600 (comment)](https://github.com/prisma/prisma/issues/23600#issuecomment-2135604873), may you please another new unofficial version of Prisma, and report back if it keeps working for your scenario? `5.15.0-integration-client-dynamic-wasm-imports.1`
> 
> You can quickly install it via:
> 
> ```
> pnpm add -D prisma@5.15.0-integration-client-dynamic-wasm-imports.1;
> pnpm update "@prisma/*" 5.15.0-integration-client-dynamic-wasm-imports.1
> ```
> 
> (please double check that prisma generate has run before retrying). We expect this to be released with Prisma 5.15.0 next week. Thanks!

I'm now closing this PR in favor of https://github.com/prisma/prisma/pull/24312, which was merged and is part of the upcoming Prisma release, 5.15.0 (coming out today!).

Thanks @smorimoto for the inspiration and contribution!

**Comment by smorimoto** [comment]
@jkomyno All right. It would be more polite to set me and @nzws as co-authors on Git from now on :)
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Pull request closed without merging**
