### PR TITLE
feat(adapter-d1): fix data-type-related tests in prisma-engines

### PR DESCRIPTION
**Pull request by jkomyno**
This PR fixes tests in the `data-type` bucket for D1.

### CODE REVIEW

**Comment by jkomyno** [comment]
(@Jolg42, wait for review please, there are failing tests)

**Comment by jkomyno** [comment]
> (@Jolg42, wait for review please, there are failing tests)

Looks like failures are related to https://github.com/prisma/prisma/pull/23472, I'm investigating some more now.

**Comment by jkomyno** [comment]
> > (@Jolg42, wait for review please, there are failing tests)
> 
> Looks like failures are related to #23472, I'm investigating some more now.

This is probably fixed by https://github.com/prisma/prisma-engines/pull/4786.

**Review by Jolg42 — APPROVED** [review]

**Comment by jkomyno** [comment]
Next step: merge branch `integration/engines-5.12.0-10.integration-jkomyno-d1-boolean-904260f081dd153649eb6e22e36baeb9cb0a0da1` (via https://github.com/prisma/prisma/pull/23593)

**Comment by jkomyno** [comment]
I currently get a single [failure](https://github.com/prisma/prisma/actions/runs/8394806570/job/22992823363?pr=23563#step:5:275):

```
FAIL raw-queries/typed-results/tests.ts
  ● raw-queries.typed-results (provider=sqlite, js_d1) › query model with a BigInt = MAX_SAFE_INTEGER

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      148 |         expect(result![0].bInt === 9007199254740991).toBe(true)
      149 |       } else {
    > 150 |         expect(result![0].bInt === BigInt('9007199254740991')).toBe(true)
          |                                                                ^
      151 |       }
      152 |     })
      153 |

      at Object.<anonymous> (raw-queries/typed-results/tests.ts:150:64)

  ● raw-queries.typed-results (provider=sqlite, js_d1) › query model with a BigInt = -MAX_SAFE_INTEGER

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      167 |       } else {
      168 |         // It's a bigint
    > 169 |         expect(result![0].bInt === BigInt('-9007199254740991')).toBe(true)
          |                                                                 ^
      170 |       }
      171 |     })
      172 |

      at Object.<anonymous> (raw-queries/typed-results/tests.ts:169:65)
```

Which does NOT happen locally..

**Pull request merged**
