### PR TITLE
test(client): unskip 2 tests using the isolated postgresql / mysql uris

### PR DESCRIPTION
**Pull request by Jolg42**

### CODE REVIEW

**Comment by millsp** [comment]
I think it could be worth porting this to the functional tests (+ all dbs are isolated by default there).

**Comment by Jolg42** [comment]
@millsp I think someone from Client Team could finish that then

**Comment by millsp** [comment]
I am OK merging this for now, because everyone is fully booked atm

**Comment by Jolg42** [comment]
👍🏼 I'll check later, maybe the easy option would be to disable them for the `no-docker` runs

**Review by millsp — APPROVED** [review]

**Pull request merged**
