### PR TITLE
test(client,sdk,integration-tests): remove --forceExit

### PR DESCRIPTION
**Pull request by millsp**
Figuring why tests are blocking jest from finishing:

- [ ] migrate
- [ ] E2E
- [x] sdk
- [x] client
- [x] integration-tests
- [x] workflows

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/prisma/e2e-tests%24+forceExit&patternType=literal
https://sourcegraph.com/search?q=context:global+repo:github.com/prisma/prisma+--forceExit+count:1000&patternType=literal

Partially fulfills https://github.com/prisma/prisma/issues/7795

### CODE REVIEW

**Comment by millsp** [comment]
So the open handle problem has been fixed for BuildKite and locally, but GH Actions freezes.

**Comment by millsp** [comment]
Ok, so `@prisma/client` is done, see commits for the two little changes.

**Comment by Jolg42** [comment]
Nice!! Would be good to merge this in chunks, and create other PR maybe if fixing all of them takes long.

**Comment by Jolg42** [comment]
@millsp I think we could merge this soon and create new PRs for the others?

**Comment by millsp** [comment]
Ok let me look if I can remove the remaining `--forceExit` without too much work. If not, then I'll create a separate PR.

**Comment by millsp** [comment]
`migrate` has a few suites not exiting properly. And we still need to disable `--forceExit` E2E.

**Review by Jolg42 — APPROVED** [review]
Nice! Well done 👍🏼

**Pull request merged**
