### PR TITLE
test: run studio test for Node-API too

### PR DESCRIPTION
**Pull request by Jolg42**
For Studio test in CLI

Before enabling testing with Node-API we saw that the CLI test was never ending for we don’t know the reason.

Now that it’s enabled for Node-API
It’s both cli tests, binary and Node-API that never ends
https://github.com/prisma/prisma/pull/7680

```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

@madebysid thinks a prisma.$disconnect is probably missing somewhere.

### CODE REVIEW

**Comment by Jolg42** [comment]
We can merge after release

**Review by millsp — APPROVED** [review]

**Comment by williamluke4** [comment]
image (2)
I have merged this [PR](https://github.com/prisma/prisma/pull/7739), Which adds `--forceExit` as a temp workaround

**Comment by Jolg42** [comment]
Looks like it's ready to be merged

**Comment by Jolg42** [comment]
Looks like tests are failing now, @madebysid maybe you know why

**Comment by Jolg42** [comment]
Thanks @madebysid 🙇‍♂️

**Pull request merged**
