### PR TITLE
Fixed npm package installation command syntax

### LINKED ISSUE #1247: CLI tries to download npm packages using `npm add`
https://github.com/prisma/prisma2/blob/34f5e82d201fc5ceaad6041bf670838161188f1b/cli/sdk/src/predefinedGeneratorResolvers.ts#L88-L90

It tries to download packages using `npm add` even though npm packages are installed using `npm install`

### PR DESCRIPTION
**Pull request by ghost**
Fixes #1247

### CODE REVIEW

**Review by pantharshit00 — APPROVED** [review]
~Nice catch :).~

**Comment by pantharshit00** [comment]
`npm install` is an alias to `npm add`. I missed that at first. This makes this PR irrelevant.

I am going to close this now but thanks for your contribution.

**Comment by janpio** [comment]
This is actually not irrelevant, as the common and known command to users indeed is called `npm install`. As the command indeed seems to confuse users, this is a valuable change that will help avoid such confusion in the future.

**Comment by timsuchanek** [comment]
Thanks for the PR!

**Comment by 17520605** [comment]
K

**Pull request merged**
