### PR TITLE
chore: list all shadowed vars

### PR DESCRIPTION
**Pull request by Jolg42**
It seems we have some shadowing of variables in our codebase.

This PR is to enforce the eslint rule and cleanup the codebase.

https://eslint.org/docs/rules/no-shadow

Current status (outdated):
- [ ] cli ✖ 4 problems (3 errors, 1 warning)
- [ ] client ✖ 55 problems (39 errors, 16 warnings)
- [ ] debug ✖ 1 problem (1 error, 0 warnings)
- [ ] engine-core ✖ 11 problems (8 errors, 3 warnings)
- [ ] generator-helper ✖ 1 problem (1 error, 0 warnings)
- [ ] migrate ✖ 10 problems (7 errors, 3 warnings)
- [ ] integration-tests ✖ 4 problems (3 errors, 1 warning)
- [ ] eact-prisma ✖ 5 problems (5 errors, 0 warnings)
- [ ] sdk ✖ 14 problems (11 errors, 3 warnings)

### CODE REVIEW

**Review by millsp — CHANGES_REQUESTED** [review]
Maybe make this a draft and fix all the shadowed vars?

**Comment by Jolg42** [comment]
Yes cleanup needs to happen now

**Comment by Jolg42** [comment]
@do4gr Your PR https://github.com/prisma/prisma-engines/pull/2262 seems to have a side effect here 

Schema is https://github.com/prisma/prisma/blob/main/packages/client/src/__tests__/integration/happy/exhaustive-schema/schema.prisma#L111

Side effect is that the generated client gets one more line
```diff
        export type OptionalSide1WhereUniqueInput = {
          id?: number
+         optionalSide2Id?: number
        }
```

Is this expected?

**Comment by jkomyno** [comment]
This should be deprecated by https://github.com/prisma/prisma/pull/13975

**Comment by Jolg42** [comment]
Note: Latest run reports 250 errors
https://github.com/prisma/prisma/actions/runs/5832133060/job/15816938429?pr=7674#step:5:1084

**Comment by Jolg42** [comment]
Closing as we have https://github.com/prisma/team-orm/issues/273 as tracking issue

**Pull request closed without merging**
