### PR TITLE
fix(adapter-neon): fix type parsing for PrismaNeonHTTP adapter

### LINKED ISSUE #25514: `PrismaNeonHTTP` adapter breaks on some types e.g. timestamp
### Bug description

The PrismaNeon adapter uses custom type parsers to address this, but these are not used by the PrismaNeonHTTP adapter.

Use of the PrismaNeonHTTP adapter fails when encountering certain datatypes. e.g. timestamp (returned from the @neondatabase/serverless driver as a javascript `Date` object when Prisma expects a string)

```
Error: Inconsistent column data: Conversion failed: expected a string in column '<columnname>', found {}
```

or with simple `$queryRaw`

```
await prisma.$queryRaw`SELECT NOW()`

Raw query failed. Code: `N/A`. Message: `N/A`
```

### How to reproduce

Use PrismaNeonHTTP adapter

Any query that returns an unsupported data type, e.g.

```
await prisma.$queryRaw`SELECT NOW()`
```

### Expected behavior

_No response_

### Prisma information

Latest prisma v5.21.1

### Environment & setup

Latest prisma v5.21.1

### Prisma Version

```
Latest prisma v5.21.1
```

### PR DESCRIPTION
**Pull request by andyjy**
fixes https://github.com/prisma/prisma/issues/25514

~~requires bumping peer dep to latest `@neondatabase/serverless` version, once https://github.com/neondatabase/serverless/pull/110 is merged and released~~ 
=> devDependency now bumped to `@neondatabase/serverless@0.10.2` to fix types

This PR simply duplicates passing the existing type parsers as already used for the `PrismaNeon` adapter.

should continue to work with any version of `@neondatabase/serverless` as a peer dep: 
- this fix will have no effect unless used with `@neondatabase/serverless` >= `0.9.5`
- for versions of `@neondatabase/serverless < `0.9.5` the addition of `types` option will be silently ignored

The [original PR adding type parsers to `PrismaNeon`](https://github.com/prisma/prisma/pull/24434) didn't add tests for correct type conversion so I wasn't able to easily repurpose any existing tests for type conversion.

### CODE REVIEW

**Comment by aqrln** [comment]
> The https://github.com/prisma/prisma/pull/24434 didn't add tests for correct type conversion so I wasn't able to easily repurpose any existing tests for type conversion.

It should in theory be covered by the existing tests. I'm not sure though if the HTTP Neon client is used in tests at all since it doesn't support transactions.

**Review by aqrln — APPROVED** [review]
LGTM if you can confirm this fixes the issue for you

**Comment by andyjy** [comment]
> LGTM if you can confirm this fixes the issue for you

Thanks! Yes this fixes the issue; I have been using this successfully via a patch in the interim.

**Comment by aqrln** [comment]
Cool! I'll go ahead and merge it then.

**Pull request merged**
