### PR TITLE
refactor: drop support for Node.js 10

### LINKED ISSUE #7394: Dropping Node v10 support (LTS reached EndOfLife)
For Prisma Client / Prisma CLI we need to drop Node.js v10 (now old LTS)

Its End Of Life was on April 30 (for Security Support) and Active Support was dropped last year in May 2020.

Happy to do it/pair on this since I know where changes are needed.

The outcome will be that we support Node >=12.2.X and >=14.X (v16 is supported but not LTS yet, not recommended for production)

See current version https://www.prisma.io/docs/reference/system-requirements

## Additional context
https://prisma-company.slack.com/archives/C1FPU5FPT/p1621436107007300

### PR DESCRIPTION
**Pull request by millsp**
Closes #7394

:warning: Do not merge

Need to merge https://github.com/prisma/e2e-tests/pull/1776 first

### CODE REVIEW

**Comment by janpio** [comment]
Optimally we get e2e tests happy via https://prisma-company.slack.com/archives/CRGDU19K6/p1623262420049000 for the integration branch before this is merged.

**Comment by janpio** [comment]
The Buildkite tests failures are also pretty weird. If this might be Node-API flakyness we need to investigate.

**Comment by millsp** [comment]
It is strange indeed since I cannot reproduce this locally (ubuntu) but fails consistently on buildkite (3 retries).

**Comment by Jolg42** [comment]
Note `chore` does not really fit here no?,

Maybe `refactor?`

From CONTRIBUTING:
List of types:

    feat: A new feature
    fix: A bug fix
    docs: Documentation only changes
    style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    refactor: A code change that neither fixes a bug nor adds a feature
    perf: A code change that improves performance
    test: Adding missing or correcting existing tests
    chore: Changes to the build process or auxiliary tools and libraries such as documentation generation

**Comment by janpio** [comment]
@millsp Please raise this in our #proejct-node-api channel so @williamluke4 can handle it.

**Review by janpio — APPROVED** [review]

**Pull request merged**
