### PR TITLE
fix(engine-core): allow library engine to reestablish connection after initial error

### LINKED ISSUE #12028: Unable to establish a connection once database recovers
## Bug description

If the initial request is sent while database connection cannot be established, all subsequent request will result in failures.

 ## Steps reproduction

1) Take down database
2) Initiate request `prisma.$queryRaw` (FAILS)
3) Bring up database
4) Initiate request `prisma.$queryRaw` (FAILS)

Both requests fail with
```
Can't reach database server at xxxx:xxx
```
```
  prisma:client:libraryEngine sending request, this.libraryStarted: false +5s
  prisma:client:libraryEngine library starting +0ms
  prisma:info Starting a postgresql pool with 21 connections.
  prisma:client:libraryEngine sending request, this.libraryStarted: false +7s
  prisma:client:libraryEngine library already starting, this.libraryStarted: false +0ms
```

## Expected Behavior

1) Take down database
2) Initiate request `prisma.$queryRaw` (FAILS)
3) Bring up database
4) Initiate request `prisma.$queryRaw` (PASSES)

See PR https://github.com/prisma/prisma/pull/12066

### PR DESCRIPTION
**Pull request by chronotc**
Fixes https://github.com/prisma/prisma/issues/12028

Looking for some help with unit tests ....

### CODE REVIEW

**Comment by janpio** [comment]
Can you explain the change and why it could/should help?

**Comment by chronotc** [comment]
Currently we have checks

https://github.com/prisma/prisma/blob/b2390904be1a36559b1f4b9190c0168b9a1b0bd2/packages/engine-core/src/library/LibraryEngine.ts#L327-L330

to preventing an LibraryEngine from starting if it is already in the process of starting.

On a successful `connect()`, this promise is set to `undefined` giving the ability for LibraryEngine to be started again. This is not the case on failed a `connect()` as this statement is missing from the catch.

In order to ensure that LibraryEngine can be restarted on successful and failed `connect()`, the promise is set to `undefined` to provide consistent behaviour.

In our particular use case, we have a middleware setup to retry any request. Due the current behaviour, this is preventing retries from working entirely if the initial `connect()` results in a failure.

**Comment by janpio** [comment]
Nice. So currently it is missing in https://github.com/prisma/prisma/blob/7f0ad73f46c8b2e91b8ab05f4e16c88ceb267f04/packages/engine-core/src/library/LibraryEngine.ts#L342-L351 - and moving it to the `finally` solves that?

**Comment by chronotc** [comment]
@janpio . Yep! 😄

**Comment by chronotc** [comment]
@Jolg42 , is there anything I could do to help move this forward?

**Comment by garrensmith** [comment]
@chronotc I accidentally wrote the exact fix for this. I can confirm that your code fix is the correct one. 

This is my PR https://github.com/prisma/prisma/pull/12587
but lets rather use your PR.

**Review by millsp — APPROVED** [review]

**Comment by sreuter** [comment]
Most excellent, thank you so much @garrensmith @millsp @chronotc and co.! Can't wait to take that for a spin tomorrow!

**Pull request merged**
