### PR TITLE
fix(client): Reexporting in the way that cjs-module-lexer can detect

### PR DESCRIPTION
**Pull request by tnzk**
# Background

Users of Svelte Kit, Nuxt or other Vite based frameworks haven't been able to import PrismaClient or other exports in the way the documentation suggests[^1]. While there's [several](https://github.com/prisma/prisma/discussions/9027#discussion-3548083) [workarounds](https://github.com/prisma/prisma/issues/5030#issuecomment-970157451) [known](https://www.mikenikles.com/blog/svelte-kit-prisma-a-match-made-in-digital-heaven#commento-comment-name-c13f447ec60eb97a32ae2cb8fe7aaabd760208be22be65d1345f533c5a51f251) in the community, they still have some shortcomings like inability to import Enum values or `Prisma` object for SQL templates nicely.

Those frameworks emit ES modules as their build artifacts, unlike Next that emits CJS bundles. When an ES module tries to `import` named exports from other CJS modules, Node recognizes only the exports that detected in static analysis for specific patterns. [^2]

> For better compatibility with existing usage in the JS ecosystem, Node.js in addition attempts to determine the CommonJS named exports of every imported CommonJS module to provide them as separate ES module exports using a static analysis process.
> 
> The detection of named exports is based on common syntax patterns but does not always correctly detect named exports.

Because of this, current glue code just reexports default export from perspective of Node, while TS compiler somehow recognized the named exports. This causes a weird situation where they would work fine in dev server, but fails with the error message like this once they have been bundled for production, as ES modules with static `import` s.

# Solution

This PR proposes to change the glue code to the form[^3] that Node can recognize all the reexporting of named exports.

[^1]: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/instantiate-prisma-client
[^2]: https://nodejs.org/api/esm.html#commonjs-namespaces
[^3]: https://github.com/nodejs/cjs-module-lexer/tree/1.2.2

I'm relatively new to Prisma, and this is my first PR here. I've confirmed tests below `packages/client` passed, but please tell me if anything need to be merged

### CODE REVIEW

**Comment by janpio** [comment]
Amazing 🥇 Thanks for doing this!

We have https://github.com/prisma/ecosystem-tests, where we try to have test projects in all forms and colors where something around Prisma could be going wrong - and seems you mentioned a class of projects that would be worth adding there. Right now they obviously would all be failing, but with your PR here merged they would then succeed - correct? If so, it would be great if you could help us actually create these projects over there. The setup is not the easiest, so maybe just start with an issue where you describe what kind of projects would be missing and then we discuss from there how you can best help us set up a minimal project we can add there.

(I also approved the test run on this PR so you get our CI feedback soon as well)

**Comment by tnzk** [comment]
Sure, ecosystem tests seem interesting! I'll make an issue as a starter and try adding the projects in Svelte Kit if possible.

**Review by aqrln — APPROVED** [review]

**Comment by aqrln** [comment]
This looks good to me, thank you!

@janpio is there anything that still needs to be done before merging this (e.g., related to ecosystem tests)? If not, this looks ready to merge to me.

**Comment by husayt** [comment]
this assumes that output is going to be ".prisma". What about overriding `output` in schema, if I set `output  = "/myprisma/client"` then it should use that not `.prisma`

**Pull request merged**
