### PR TITLE
feat(client): add forceInlineSchema generator parameter

### LINKED ISSUE #13052: Inline/bundle the contents of the prisma schema on generate
We could close a whole class of issues where the schema is not found (https://github.com/prisma/prisma/labels/topic%3A%20ENOENT%20schema.prisma) by inlining the contents of the `schema.prisma` directly into the generated `index.js`. Our logic happens to break usually when code is bundled (nextjs, svelte, webpack).

When code is bundled to another location, our lookup paths for the schema do not make sense any longer. We have logic to at best find the original generated folder, which works at best but has not guarantee it could find the correct folder and fails especially on monorepos.

A solution to this is to directly embed the prisma schema, which needs to be passed to the engines. Side note: We might experience the same thing again for sqlite databases since we resolve their normal location relatively to the generated client.

### PR DESCRIPTION
**Pull request by itamar-getloam**
Closes #13052

### CODE REVIEW

**Review by Jolg42 — CHANGES_REQUESTED** [review]
Thanks for the PR!

I think @millsp is working on something similar at the moment, so I'm blocking the PR for now, since it's something that @millsp should check before you continue here.

**Comment by millsp** [comment]
Hey @itamar-getloam, we are planning to make this a thing https://github.com/prisma/prisma/pull/13261 https://github.com/prisma/prisma/issues/13052

**Comment by itamar-getloam** [comment]
Appreciate the super quick response! @Jolg42 @millsp
Your solution is definitely the better way to go, replacing all `datamodelPath` with `inlineSchema` is much cleaner than the temp file solution I implemented.

Could you give a rough estimation regarding the time it will take to merge your fixes?

Thanks!

**Comment by millsp** [comment]
Thanks, we appreciate your contribution and interest in Prisma. I can't tell you when it will be merged, probably less than 2 weeks for sure. But I can give you an integration version to try it out in a few days (don't hesitate to ping me again :) )

**Pull request closed without merging**
