### PR TITLE
fix: group by aggregate

### PR DESCRIPTION
**Pull request by timsuchanek**

### CODE REVIEW

**Review by millsp — APPROVED** [review]

**Comment by millsp** [comment]
I restarted the build for https://github.com/prisma/prisma/pull/6520 to kick in, but tests are still failing on Node 14 in `setup.ts`.

**Comment by timsuchanek** [comment]
Hmm that didn't work out. I just merged `master`, let's see if that helps

**Comment by Jolg42** [comment]
@timsuchanek master is red for GitHub Actions after your merge, could you check that now?
https://github.com/prisma/prisma/runs/2324378489
Screen Shot 2021-04-12 at 15 55 38

**Comment by Jolg42** [comment]
Also fails for https://github.com/prisma/prisma/pull/6528

**Comment by timsuchanek** [comment]
I'll have a look!

**Comment by Jolg42** [comment]
Also fails in https://github.com/prisma/prisma/pull/6217 🤔

**Comment by Jolg42** [comment]
Note: Thanks for fixing it with https://github.com/prisma/prisma/commit/e81740b9326569036f0afe20405af13b8fe69773 (it was not related to this PR in the end)

**Pull request merged**
