### PR TITLE
fix: Unskip failing test in planetscale related to dates

### PR DESCRIPTION
**Pull request by miguelff**
Close https://github.com/prisma/team-orm/issues/517

Requires https://github.com/prisma/prisma-engines/pull/4422 to be merged and integrated into prisma/prisma before merging

### CODE REVIEW

**Review by janpio — APPROVED** [review]

**Comment by miguelff** [comment]
Waiting to update prisma main with latest engines' after merging https://github.com/prisma/prisma-engines/pull/4422, There's a PR open for the integration branch in https://github.com/prisma/prisma/pull/21831 and I'm looking for an (a priori unrelated) failing test

**Comment by miguelff** [comment]
Actually the offending test in https://github.com/prisma/prisma/pull/21831 passes locally, so I will merge this PR as soon as the new version of engines is published and bumped either in main or here (whatever happens before)

```
❯ pe && cargo build -p query-engine-node-api && p && cd packages/client && PRISMA_QUERY_ENGINE_LIBRARY=/Users/miguel/GitHub/prisma/prisma-engines/target/debug/libquery_engine.dylib && pnpm run test:functional:code  --flavor=js_planetscale 15176
    Finished dev [unoptimized + debuginfo] target(s) in 0.64s

> @prisma/client@0.0.0 test:functional:code /Users/miguel/GitHub/prisma/prisma/packages/client
> dotenv -e ../../.db.env -- node -r esbuild-register helpers/functional-test/run-tests.ts --no-types "--flavor=js_planetscale" "15176"

{
  column: 28,
  file: '/Users/miguel/GitHub/prisma/prisma/packages/engines/dist/index.js',
  length: 2,
  line: 16652,
  lineText: '          } else if (x2 === -0) {',
  namespace: '',
  suggestion: ''
}
Comparison with -0 using the "===" operator will also match 0
 PASS  tests/functional/issues/15176/tests.ts (5.547 s)
  issues.15176 (provider=sqlite)
    ○ skipped should update both updatedAt fields on a model
  issues.15176 (provider=sqlite, js_libsql)
    ○ skipped should update both updatedAt fields on a model
  issues.15176 (provider=postgresql)
    ○ skipped should update both updatedAt fields on a model
  issues.15176 (provider=postgresql, js_pg)
    ○ skipped should update both updatedAt fields on a model
  issues.15176 (provider=postgresql, js_neon)
    ○ skipped should update both updatedAt fields on a model
  issues.15176 (provider=mysql)
    ○ skipped should update both updatedAt fields on a model
  issues.15176 (provider=mysql, js_planetscale)
    ✓ should update both updatedAt fields on a model (97 ms)
  issues.15176 (provider=mongodb)
    ○ skipped should update both updatedAt fields on a model
  issues.15176 (provider=cockroachdb)
    ○ skipped should update both updatedAt fields on a model
  issues.15176 (provider=sqlserver)
    ○ skipped should update both updatedAt fields on a model

Test Suites: 1 passed, 1 total
Tests:       9 skipped, 1 passed, 10 total
Snapshots:   0 total
Time:        5.579 s
Ran all test suites matching /15176/i.
```

**Review by aqrln — APPROVED** [review]

**Comment by Jolg42** [comment]
I actually merged the PR, but it was indeed not flaky. 😅 
https://github.com/prisma/prisma/pull/21832#issuecomment-1801350061

See the failing test for Planetscale, it's the same error in this PR now that it's sync with main

**Comment by Jolg42** [comment]
So technically not blocking this PR, but someone needs to have a look

**Comment by miguelff** [comment]
I'm taking a look.

**Comment by miguelff** [comment]
Ok, fix: https://github.com/prisma/prisma-engines/pull/4426, The reason for the flakeyness, is that there is a lag between the create and the update, of up to a hundred milleseconds. Sometimes that makes it to the next second since epoch and the test passed. There was an underlying bug, tho DateTimes didn't include franctionals in main.

I'm merging this, in the light of https://github.com/prisma/prisma-engines/pull/4426

**Pull request merged**
