### PR TITLE
chore: move prisma version down in issue template

### PR DESCRIPTION
**Pull request by RafaelKr**
this would make more sense, as it is a multi-line output

### CODE REVIEW

**Review by pantharshit00 — APPROVED** [review]
👍

**Review by janpio — APPROVED** [review]
👍 

(Needs to be applied to all other repos as well @pantharshit00)

**Comment by RafaelKr** [comment]
Another thing I would like to suggest is that directory paths in the output of `prisma -v` should be hidden, so it doesn't leak private information.

I have structured my folder structure like `/home/rafael/coding/<CLIENT>/<PROJECT_NAME>` and I'm working on some projects where this info shouldn't be disclosed.

for example paths could be replaced with `<PROJECT_DIR>` or some other replacements if it it's another path 
```
@prisma/cli          : 2.1.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 4440772035795a0424be62040e2295c56e5c6ad0 (at <PROJECT_DIR>/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 4440772035795a0424be62040e2295c56e5c6ad0 (at <PROJECT_DIR>/node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 4440772035795a0424be62040e2295c56e5c6ad0 (at <PROJECT_DIR>/node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 4440772035795a0424be62040e2295c56e5c6ad0 (at <PROJECT_DIR>/node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
```

**Comment by janpio** [comment]
Related @RafaelKr : https://github.com/prisma/prisma/issues/2882

**Comment by RafaelKr** [comment]
Wow, 18 hours ago :D thanks for linking this @janpio!

**Comment by Jolg42** [comment]
@pantharshit00 I can merge this if you want but as the change is needed in the other repos I guess it's better if you do it :)

**Comment by pantharshit00** [comment]
Sorry for the delay here 🙏 

@Jolg42 Please merge this PR and these other PRs: https://github.com/prisma/prisma-client-js/pull/796 and https://github.com/prisma/migrate/pull/524

**Comment by janpio** [comment]
Did that as @Jolg42 is on vacation right now.

**Comment by RafaelKr** [comment]
Awesome, thanks!

**Pull request merged**
