### PR TITLE
fix(README): add `npx` in front of `prisma generate`

### PR DESCRIPTION
**Pull request by miguelgargallo**
I correct 1 crucial command for starters or begginers,
always all commands must proceed with "npx" at the beggining.

### CODE REVIEW

**Review by nikolasburk — APPROVED** [review]
Thanks for catching this @miguelgargallo 🎉 we indeed want to encourage people to prefix all `prisma` command with `npx` as a best practice!

**Review by Jolg42 — APPROVED** [review]

**Comment by Jolg42** [comment]
@miguelgargallo Could you sign the CLA here https://github.com/prisma/prisma/pull/15125#issuecomment-1233353700

Let me know if you have any issue with it

**Comment by Jolg42** [comment]
@miguelgargallo Did you try signing the CLA? the status is `not signed yet` 🤔

**Comment by miguelgargallo** [comment]
Omg i am trying but i cant

**Comment by miguelgargallo** [comment]
Did I sign it? due to cache browser problems I had to format the computer

**Comment by miguelgargallo** [comment]
> Thanks for catching this @miguelgargallo 🎉 we indeed want to encourage people to prefix all `prisma` command with `npx` as a best practice!

Thank you miguelgargallo
for signing the CLA!

We are now taking you back to GitHub

**Comment by miguelgargallo** [comment]
Team Prisma! My apologize, I fix my browser problem and could sign the CLA!!! My apologize!

**Review by janpio — APPROVED** [review]

**Pull request merged**
