### PR TITLE
chore(integration): add support for JS connectors 

### PR DESCRIPTION
**Pull request by jkomyno**
Integration PR for https://github.com/prisma/prisma/pull/20507.

### CODE REVIEW

**Comment by Jolg42** [comment]
I'll make it ready to review to try out if that changes anything 🤔

**Comment by jkomyno** [comment]
@Jolg42 Note as to why the PR wasn't marked as "Ready to review": client tests are failing, our priority is releasing an integration version and not fixing them, and we shouldn't lead anyone to think we should merge this PR (as it impacts the public API of the Prisma Client, which the "Node Modules DX" team hasn't agreed on yet).

**Comment by Jolg42** [comment]
Yes, understandable, I don't think it should change anything though it was something to try out, an integration version is in progress for this branch now.

**Comment by jkomyno** [comment]
Closing in favor of https://github.com/prisma/prisma/pull/20507.

**Pull request closed without merging**
