### PR TITLE
fix(client): Set Class Name For Errors

### PR DESCRIPTION
**Pull request by zhiyan114**
This is added to allow error reporting software (such as `sentry.io`) to correctly label the errors instead of showing the default name (`Error`).

### CODE REVIEW

**Review by aqrln — APPROVED** [review]
Thank you!

**Comment by aqrln** [comment]
It looks like some snapshot tests are failing and need to be updated: https://github.com/prisma/prisma/actions/runs/5179208896/jobs/9331762758?pr=19615

**Comment by janpio** [comment]
File should be `packages/client/tests/e2e/platform-caching-error/tests/vercel-auto-generate.ts` @zhiyan114

**Comment by zhiyan114** [comment]
> It looks like some snapshot tests are failing and need to be updated: https://github.com/prisma/prisma/actions/runs/5179208896/jobs/9331762758?pr=19615

Updated! Looks like we won't be able to have a perfect test score lol.

**Review by Jolg42 — APPROVED** [review]

**Comment by Jolg42** [comment]
Note: related to https://github.com/prisma/prisma/pull/19095

**Pull request merged**
