### PR TITLE
feat(client): added dynamic context in middleware

### PR DESCRIPTION
**Pull request by Rupikz**
## Problem
This problem is well described here: https://github.com/prisma/prisma/discussions/13366

## Solution

Creation example:
```ts
prisma.findMany({
  context: {
    cache: 500
  }
})
```

Use example in middleware: 
```ts
prisma.$use((params, next) => {
  // Get params.context...
  console.log(params.context)
  return next(params)
})
```

### CODE REVIEW

**Comment by millsp** [comment]
Related: https://github.com/prisma/prisma/pull/9759

**Comment by raqfc** [comment]
Hey guys, any updates on this?? Really need this feature for my implementation.

**Comment by zibra** [comment]
LGTM!

**Comment by SevInf** [comment]
I apologize for the delay from our side.
Since middlewares are deprecated, we don't currently plan to add new features to them and we are going to close this PR.

Client extensions allow to create independent context-specific lightweight prisma client "forks". The pattern for using this:


```ts
const prisma = new Prisma()
app.get('/some-path', (request) => {
   const localPrisma = prisma.$extends(someSessionSpecificExtension(request))
   // use localPrisma while handling the request
})
```

From all extension components, [query extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions/query) are  conceptually closest to the middlewares and most middlewares should be convertable to query extension.

If you encounter any problems with this pattern or it does not fit your usecases, feel free to open an issue.

**Pull request closed without merging**
