### PR TITLE
fix(sdk): pnpm installation

### LINKED ISSUE #7484: Entity types cannot be resolved in PNPM monorepo
### Bug description

In a monorepo with **PNPM** workspace, `@prisma/client` is resolved to the `<monorepo_rootdir>/node_modules` rather than the `node_modules` under the project which depends on Prisma directly.

For example:

* <ProjectRoot>
  * packages
    * webclient
    * server (which has the dependency on `@prisma/client`)

`@prisma/client` is resolved to `ProjectRoot/node_modules` rather than `packages/server/node_modules`, which causes entity types cannot be resolved:

```
$ pnpx tsc
src/script.ts:1:24 - error TS2305: Module '"../node_modules/@prisma/client"' has no exported member 'User'.

1 import { PrismaClient, User } from '@prisma/client'
                         ~~~~
```

      

### How to reproduce

I setup a tiny monorepo https://github.com/Yaojian/prisma-monorepo . 

### Expected behavior

_No response_

### Prisma information

see the github source

### Environment & setup

- OS: Windows
- Database: Sqlite
- Node.js version: 14.15.5

### Prisma Version

```
prisma               : 2.24.1                                                                                
@prisma/client       : 2.24.1                                                                                
Current platform     : windows                                                                               
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at ..\..\node_modules\.pnpm\reg
istry.nlark.com+@prisma+engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4\node_modules\@prisma\engine
s\query-engine-windows.exe)                                                                                  
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at ..\..\node_modules\.
pnpm\registry.nlark.com+@prisma+engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4\node_modules\@prism
a\engines\migration-engine-windows.exe)                                                                      
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at ..\..\node_modules\.pn
pm\registry.nlark.com+@prisma+engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4\node_modules\@prisma\
engines\introspection-engine-windows.exe)                                                                    
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at ..\..\node_modules\.pnpm\regis
try.nlark.com+@prisma+engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4\node_modules\@prisma\engines\
prisma-fmt-windows.exe)                                                                                      
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4                                              
Studio               : 0.397.0                                                                               
```

### LINKED ISSUE #7934: 2.26.0 and `pnpm` do not play well together
> Is it possible to take a look at what is going on trying to use 2.26.0 with pnpm? version 2.23.0 works just fine and in every project I use prisma I had to pin the version to 2.23.0
>
> Minimal repo reproducing this issue with some instructions and screenshots in the README:
>
> https://github.com/PabloSzx/pnpm-prisma-bug

_Originally posted by @PabloSzx in https://github.com/prisma/prisma/discussions/7925#discussioncomment-939511_

### PR DESCRIPTION
**Pull request by millsp**
Fixes https://github.com/prisma/prisma/issues/7934
Fixes https://github.com/prisma/prisma/issues/7484

Additionally, I added the necessary tests to E2E.

E2E https://github.com/prisma/e2e-tests/actions/runs/984959475

### CODE REVIEW

**Comment by matthewmueller** [comment]
This might be able to close this issue: https://github.com/prisma/prisma/issues/5340

**Comment by millsp** [comment]
We are just getting things ready in `E2E` then we are good to go.

**Review by williamluke4 — APPROVED** [review]
Awesome work :tada:

**Comment by Jolg42** [comment]
@millsp I think we should merge this now, could you fix the conflict?

**Comment by Jolg42** [comment]
Seems still conflicting 🤔

**Review by Jolg42 — APPROVED** [review]
Looks great!

**Pull request merged**
