### PR TITLE
feat: add TS types for DB native type attributes from DMMF

### PR DESCRIPTION
**Pull request by pasha-vuiko**
Adding native types attributes data.

Linked to https://github.com/prisma/prisma-engines/pull/5009

### CODE REVIEW

**Comment by pasha-vuiko** [comment]
@aqrln I pushed cherry picked changes, but looks like now tests are failing because some other changes from prisma-engines were added

**Comment by aqrln** [comment]
@pasha-vuiko I'll just merge your engines PR and take care of integration. Thanks so much for doing this!

**Comment by pasha-vuiko** [comment]
@aqrln thank you so much!

**Comment by aqrln** [comment]
Closing in favour of https://github.com/prisma/prisma/pull/25722.

**Pull request closed without merging**
