### PR TITLE
test(client): use PostgreSQL instead of SQLite in iTX tests

### PR DESCRIPTION
**Pull request by aqrln**
Concurrent transactions test doesn't always work with SQLite because SQLite doesn't support concurrent writes.

Before:

```
❯ detect_flake --command "pnpm --filter @prisma/client test -- interactive-transactions" --threads 3
█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 3/3
Success: 1/3
Failure: 2/3

❯ detect_flake --command "pnpm --filter @prisma/client test -- interactive-transactions" --threads 10
███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10/10
Success: 0/10
Failure: 10/10
```

After:

```
❯ detect_flake --command "pnpm --filter @prisma/client test -- interactive-transactions" --threads 10
███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 10/10
Success: 10/10
Failure: 0/10

❯ detect_flake --command "pnpm --filter @prisma/client test -- interactive-transactions" --threads 10 --runs-per-thread 2
███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 20/20
Success: 20/20
Failure: 0/20

❯ detect_flake --command "pnpm --filter @prisma/client test -- interactive-transactions" --threads 3 --runs-per-thread 10
███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 30/30
Success: 30/30
Failure: 0/30
```

(with `Math.random()` added to the database name because many tests are not reentrant).

### CODE REVIEW

**Comment by Jolg42** [comment]
Fails on buildkite with https://buildkite.com/prisma/test-prisma-typescript/builds/10435#033e0e56-9954-4845-a782-e9168bdf1a27/263-2793

Screen Shot 2021-11-22 at 15 14 38

Did a retry to see if something flaky

**Comment by aqrln** [comment]
@Jolg42 checked locally, everything works nice with `LibraryEngine`, but with `BinaryEngine` everything breaks with

```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("25P02"), message: "current transaction is aborted, commands ignored until end of transaction block", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("postgres.c"), line: Some(1591), routine: Some("exec_bind_message") }) }) })
```

as soon as I run more than one instance of tests in parallel.

**Review by millsp — APPROVED** [review]

**Comment by aqrln** [comment]
This should be more robust, I hope.

Failures with `BinaryEngine` are still worth investigating though, might or might not be potential bugs.

**Review by Jolg42 — APPROVED** [review]
Nice! 💚

**Pull request merged**
