### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by Lioness100**
This PR fixes a few misc typos

### CODE REVIEW

**Comment by janpio** [comment]
https://de.wikipedia.org/wiki/Pinguine 😆

**Comment by janpio** [comment]
We already use CSpell in docs, maybe we should add rspell to our CI :D

**Comment by Lioness100** [comment]
> [de.wikipedia.org/wiki/Pinguine](https://de.wikipedia.org/wiki/Pinguine) 😆

Haha! You learn something new every day.

> We already use CSpell in docs, maybe we should add rspell to our CI :D

 😂 This was a great repository for a trial run of rspell! Thanks so much, huge fan of prisma 💖

**Comment by janpio** [comment]
Oh sorry, I should have been more precise with my comment: The "pinguin" most probably made an entry to the codebase form a German colleague, that did not know that those are actually called "penguins" in English. We should totally fix that.

**Comment by Lioness100** [comment]
Ah, no, my fault, I shouldn't thought a bit harder about that lol

**Review by millsp — APPROVED** [review]

**Comment by millsp** [comment]
Hey @Lioness100 thanks for taking the time to make this PR

**Pull request merged**
