### PR TITLE
Update limitations.md

### PR DESCRIPTION
**Pull request by matthewmueller**

### CODE REVIEW

**Comment by janpio** [comment]
Huh what is this change about?

**Comment by matthewmueller** [comment]
image

numberssss

**Comment by janpio** [comment]
Please have a look at https://github.com/prisma/prisma2/pull/431/files @matthewmueller and @pantharshit00 then and let me know if this will still need numbered lists so I can adapt this open PR.

**Comment by pantharshit00** [comment]
No need as we have headers there. You can easily link headers in Github.

**Pull request merged**
